// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/configuration/credentials/credentials.proto

package credentials

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UNIXCredentialsConfiguration struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId            uint32                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AdditionalGroupIds []uint32               `protobuf:"varint,3,rep,packed,name=additional_group_ids,json=additionalGroupIds,proto3" json:"additional_group_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UNIXCredentialsConfiguration) Reset() {
	*x = UNIXCredentialsConfiguration{}
	mi := &file_pkg_proto_configuration_credentials_credentials_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UNIXCredentialsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UNIXCredentialsConfiguration) ProtoMessage() {}

func (x *UNIXCredentialsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_credentials_credentials_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UNIXCredentialsConfiguration.ProtoReflect.Descriptor instead.
func (*UNIXCredentialsConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_credentials_credentials_proto_rawDescGZIP(), []int{0}
}

func (x *UNIXCredentialsConfiguration) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UNIXCredentialsConfiguration) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UNIXCredentialsConfiguration) GetAdditionalGroupIds() []uint32 {
	if x != nil {
		return x.AdditionalGroupIds
	}
	return nil
}

var File_pkg_proto_configuration_credentials_credentials_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_credentials_credentials_proto_rawDesc = "" +
	"\n" +
	"5pkg/proto/configuration/credentials/credentials.proto\x12#buildbarn.configuration.credentials\"\x84\x01\n" +
	"\x1cUNIXCredentialsConfiguration\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\rR\agroupId\x120\n" +
	"\x14additional_group_ids\x18\x03 \x03(\rR\x12additionalGroupIdsBNZLgithub.com/buildbarn/bb-remote-execution/pkg/proto/configuration/credentialsb\x06proto3"

var (
	file_pkg_proto_configuration_credentials_credentials_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_credentials_credentials_proto_rawDescData []byte
)

func file_pkg_proto_configuration_credentials_credentials_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_credentials_credentials_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_credentials_credentials_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_credentials_credentials_proto_rawDesc), len(file_pkg_proto_configuration_credentials_credentials_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_credentials_credentials_proto_rawDescData
}

var file_pkg_proto_configuration_credentials_credentials_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_configuration_credentials_credentials_proto_goTypes = []any{
	(*UNIXCredentialsConfiguration)(nil), // 0: buildbarn.configuration.credentials.UNIXCredentialsConfiguration
}
var file_pkg_proto_configuration_credentials_credentials_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_credentials_credentials_proto_init() }
func file_pkg_proto_configuration_credentials_credentials_proto_init() {
	if File_pkg_proto_configuration_credentials_credentials_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_credentials_credentials_proto_rawDesc), len(file_pkg_proto_configuration_credentials_credentials_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_credentials_credentials_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_credentials_credentials_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_credentials_credentials_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_credentials_credentials_proto = out.File
	file_pkg_proto_configuration_credentials_credentials_proto_goTypes = nil
	file_pkg_proto_configuration_credentials_credentials_proto_depIdxs = nil
}
