// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/bb_virtual_tmp/bb_virtual_tmp.proto

package bb_virtual_tmp

import (
	virtual "github.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem/virtual"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Global             *global.Configuration       `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	BuildDirectoryPath string                      `protobuf:"bytes,2,opt,name=build_directory_path,json=buildDirectoryPath,proto3" json:"build_directory_path,omitempty"`
	Mount              *virtual.MountConfiguration `protobuf:"bytes,3,opt,name=mount,proto3" json:"mount,omitempty"`
	GrpcServers        []*grpc.ServerConfiguration `protobuf:"bytes,4,rep,name=grpc_servers,json=grpcServers,proto3" json:"grpc_servers,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetBuildDirectoryPath() string {
	if x != nil {
		return x.BuildDirectoryPath
	}
	return ""
}

func (x *ApplicationConfiguration) GetMount() *virtual.MountConfiguration {
	if x != nil {
		return x.Mount
	}
	return nil
}

func (x *ApplicationConfiguration) GetGrpcServers() []*grpc.ServerConfiguration {
	if x != nil {
		return x.GrpcServers
	}
	return nil
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDesc = "" +
	"\n" +
	"dgithub.com/buildbarn/bb-remote-execution/pkg/proto/configuration/bb_virtual_tmp/bb_virtual_tmp.proto\x12&buildbarn.configuration.bb_virtual_tmp\x1aagithub.com/buildbarn/bb-remote-execution/pkg/proto/configuration/filesystem/virtual/virtual.proto\x1aKgithub.com/buildbarn/bb-storage/pkg/proto/configuration/global/global.proto\x1aGgithub.com/buildbarn/bb-storage/pkg/proto/configuration/grpc/grpc.proto\"\xbf\x02\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x120\n" +
	"\x14build_directory_path\x18\x02 \x01(\tR\x12buildDirectoryPath\x12T\n" +
	"\x05mount\x18\x03 \x01(\v2>.buildbarn.configuration.filesystem.virtual.MountConfigurationR\x05mount\x12T\n" +
	"\fgrpc_servers\x18\x04 \x03(\v21.buildbarn.configuration.grpc.ServerConfigurationR\vgrpcServersBQZOgithub.com/buildbarn/bb-remote-execution/pkg/proto/configuration/bb_virtual_tmpb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),   // 0: buildbarn.configuration.bb_virtual_tmp.ApplicationConfiguration
	(*global.Configuration)(nil),       // 1: buildbarn.configuration.global.Configuration
	(*virtual.MountConfiguration)(nil), // 2: buildbarn.configuration.filesystem.virtual.MountConfiguration
	(*grpc.ServerConfiguration)(nil),   // 3: buildbarn.configuration.grpc.ServerConfiguration
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_depIdxs = []int32{
	1, // 0: buildbarn.configuration.bb_virtual_tmp.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	2, // 1: buildbarn.configuration.bb_virtual_tmp.ApplicationConfiguration.mount:type_name -> buildbarn.configuration.filesystem.virtual.MountConfiguration
	3, // 2: buildbarn.configuration.bb_virtual_tmp.ApplicationConfiguration.grpc_servers:type_name -> buildbarn.configuration.grpc.ServerConfiguration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_configuration_bb_virtual_tmp_bb_virtual_tmp_proto_depIdxs = nil
}
