// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/runner/persistent_runner.proto

package runner

import (
	worker "github.com/buildbarn/bb-remote-execution/pkg/proto/worker"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Arguments            []string               `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
	EnvironmentVariables map[string]string      `protobuf:"bytes,2,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDirectory     string                 `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	InputRootDirectory   string                 `protobuf:"bytes,4,opt,name=input_root_directory,json=inputRootDirectory,proto3" json:"input_root_directory,omitempty"`
	TemporaryDirectory   string                 `protobuf:"bytes,5,opt,name=temporary_directory,json=temporaryDirectory,proto3" json:"temporary_directory,omitempty"`
	ProcessStderrPath    string                 `protobuf:"bytes,6,opt,name=process_stderr_path,json=processStderrPath,proto3" json:"process_stderr_path,omitempty"`
	ServerLogsDirectory  string                 `protobuf:"bytes,7,opt,name=server_logs_directory,json=serverLogsDirectory,proto3" json:"server_logs_directory,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *CreateSessionRequest) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *CreateSessionRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *CreateSessionRequest) GetInputRootDirectory() string {
	if x != nil {
		return x.InputRootDirectory
	}
	return ""
}

func (x *CreateSessionRequest) GetTemporaryDirectory() string {
	if x != nil {
		return x.TemporaryDirectory
	}
	return ""
}

func (x *CreateSessionRequest) GetProcessStderrPath() string {
	if x != nil {
		return x.ProcessStderrPath
	}
	return ""
}

func (x *CreateSessionRequest) GetServerLogsDirectory() string {
	if x != nil {
		return x.ServerLogsDirectory
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExecuteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkRequest   *worker.WorkRequest    `protobuf:"bytes,2,opt,name=work_request,json=workRequest,proto3" json:"work_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSessionRequest) Reset() {
	*x = ExecuteSessionRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSessionRequest) ProtoMessage() {}

func (x *ExecuteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSessionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteSessionRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteSessionRequest) GetWorkRequest() *worker.WorkRequest {
	if x != nil {
		return x.WorkRequest
	}
	return nil
}

type ExecuteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkResponse  *worker.WorkResponse   `protobuf:"bytes,1,opt,name=work_response,json=workResponse,proto3" json:"work_response,omitempty"`
	ResourceUsage []*anypb.Any           `protobuf:"bytes,2,rep,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteSessionResponse) Reset() {
	*x = ExecuteSessionResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteSessionResponse) ProtoMessage() {}

func (x *ExecuteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteSessionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteSessionResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteSessionResponse) GetWorkResponse() *worker.WorkResponse {
	if x != nil {
		return x.WorkResponse
	}
	return nil
}

func (x *ExecuteSessionResponse) GetResourceUsage() []*anypb.Any {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDesc = "" +
	"\n" +
	"Qgithub.com/buildbarn/bb-remote-execution/pkg/proto/runner/persistent_runner.proto\x12\x10buildbarn.runner\x1aFgithub.com/buildbarn/bb-remote-execution/pkg/proto/runner/runner.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15worker_protocol.proto\"\xe8\x03\n" +
	"\x14CreateSessionRequest\x12\x1c\n" +
	"\targuments\x18\x01 \x03(\tR\targuments\x12u\n" +
	"\x15environment_variables\x18\x02 \x03(\v2@.buildbarn.runner.CreateSessionRequest.EnvironmentVariablesEntryR\x14environmentVariables\x12+\n" +
	"\x11working_directory\x18\x03 \x01(\tR\x10workingDirectory\x120\n" +
	"\x14input_root_directory\x18\x04 \x01(\tR\x12inputRootDirectory\x12/\n" +
	"\x13temporary_directory\x18\x05 \x01(\tR\x12temporaryDirectory\x12.\n" +
	"\x13process_stderr_path\x18\x06 \x01(\tR\x11processStderrPath\x122\n" +
	"\x15server_logs_directory\x18\a \x01(\tR\x13serverLogsDirectory\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"t\n" +
	"\x15ExecuteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12<\n" +
	"\fwork_request\x18\x02 \x01(\v2\x19.bazel_worker.WorkRequestR\vworkRequest\"\x96\x01\n" +
	"\x16ExecuteSessionResponse\x12?\n" +
	"\rwork_response\x18\x01 \x01(\v2\x1a.bazel_worker.WorkResponseR\fworkResponse\x12;\n" +
	"\x0eresource_usage\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\rresourceUsage2\xf6\x02\n" +
	"\x10PersistentRunner\x12Q\n" +
	"\x0eCheckReadiness\x12'.buildbarn.runner.CheckReadinessRequest\x1a\x16.google.protobuf.Empty\x12`\n" +
	"\rCreateSession\x12&.buildbarn.runner.CreateSessionRequest\x1a'.buildbarn.runner.CreateSessionResponse\x12c\n" +
	"\x0eExecuteSession\x12'.buildbarn.runner.ExecuteSessionRequest\x1a(.buildbarn.runner.ExecuteSessionResponse\x12H\n" +
	"\fCloseSession\x12 .buildbarn.runner.SessionRequest\x1a\x16.google.protobuf.EmptyB;Z9github.com/buildbarn/bb-remote-execution/pkg/proto/runnerb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: buildbarn.runner.CreateSessionRequest
	(*CreateSessionResponse)(nil),  // 1: buildbarn.runner.CreateSessionResponse
	(*SessionRequest)(nil),         // 2: buildbarn.runner.SessionRequest
	(*ExecuteSessionRequest)(nil),  // 3: buildbarn.runner.ExecuteSessionRequest
	(*ExecuteSessionResponse)(nil), // 4: buildbarn.runner.ExecuteSessionResponse
	nil,                            // 5: buildbarn.runner.CreateSessionRequest.EnvironmentVariablesEntry
	(*worker.WorkRequest)(nil),     // 6: bazel_worker.WorkRequest
	(*worker.WorkResponse)(nil),    // 7: bazel_worker.WorkResponse
	(*anypb.Any)(nil),              // 8: google.protobuf.Any
	(*CheckReadinessRequest)(nil),  // 9: buildbarn.runner.CheckReadinessRequest
	(*emptypb.Empty)(nil),          // 10: google.protobuf.Empty
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_depIdxs = []int32{
	5,  // 0: buildbarn.runner.CreateSessionRequest.environment_variables:type_name -> buildbarn.runner.CreateSessionRequest.EnvironmentVariablesEntry
	6,  // 1: buildbarn.runner.ExecuteSessionRequest.work_request:type_name -> bazel_worker.WorkRequest
	7,  // 2: buildbarn.runner.ExecuteSessionResponse.work_response:type_name -> bazel_worker.WorkResponse
	8,  // 3: buildbarn.runner.ExecuteSessionResponse.resource_usage:type_name -> google.protobuf.Any
	9,  // 4: buildbarn.runner.PersistentRunner.CheckReadiness:input_type -> buildbarn.runner.CheckReadinessRequest
	0,  // 5: buildbarn.runner.PersistentRunner.CreateSession:input_type -> buildbarn.runner.CreateSessionRequest
	3,  // 6: buildbarn.runner.PersistentRunner.ExecuteSession:input_type -> buildbarn.runner.ExecuteSessionRequest
	2,  // 7: buildbarn.runner.PersistentRunner.CloseSession:input_type -> buildbarn.runner.SessionRequest
	10, // 8: buildbarn.runner.PersistentRunner.CheckReadiness:output_type -> google.protobuf.Empty
	1,  // 9: buildbarn.runner.PersistentRunner.CreateSession:output_type -> buildbarn.runner.CreateSessionResponse
	4,  // 10: buildbarn.runner.PersistentRunner.ExecuteSession:output_type -> buildbarn.runner.ExecuteSessionResponse
	10, // 11: buildbarn.runner.PersistentRunner.CloseSession:output_type -> google.protobuf.Empty
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_persistent_runner_proto_depIdxs = nil
}
