// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/runner/runner.proto

package runner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReadinessRequest) Reset() {
	*x = CheckReadinessRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReadinessRequest) ProtoMessage() {}

func (x *CheckReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReadinessRequest.ProtoReflect.Descriptor instead.
func (*CheckReadinessRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescGZIP(), []int{0}
}

func (x *CheckReadinessRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RunRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Arguments            []string               `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
	EnvironmentVariables map[string]string      `protobuf:"bytes,2,rep,name=environment_variables,json=environmentVariables,proto3" json:"environment_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WorkingDirectory     string                 `protobuf:"bytes,3,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	StdoutPath           string                 `protobuf:"bytes,4,opt,name=stdout_path,json=stdoutPath,proto3" json:"stdout_path,omitempty"`
	StderrPath           string                 `protobuf:"bytes,5,opt,name=stderr_path,json=stderrPath,proto3" json:"stderr_path,omitempty"`
	InputRootDirectory   string                 `protobuf:"bytes,6,opt,name=input_root_directory,json=inputRootDirectory,proto3" json:"input_root_directory,omitempty"`
	TemporaryDirectory   string                 `protobuf:"bytes,7,opt,name=temporary_directory,json=temporaryDirectory,proto3" json:"temporary_directory,omitempty"`
	ServerLogsDirectory  string                 `protobuf:"bytes,8,opt,name=server_logs_directory,json=serverLogsDirectory,proto3" json:"server_logs_directory,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RunRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *RunRequest) GetEnvironmentVariables() map[string]string {
	if x != nil {
		return x.EnvironmentVariables
	}
	return nil
}

func (x *RunRequest) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *RunRequest) GetStdoutPath() string {
	if x != nil {
		return x.StdoutPath
	}
	return ""
}

func (x *RunRequest) GetStderrPath() string {
	if x != nil {
		return x.StderrPath
	}
	return ""
}

func (x *RunRequest) GetInputRootDirectory() string {
	if x != nil {
		return x.InputRootDirectory
	}
	return ""
}

func (x *RunRequest) GetTemporaryDirectory() string {
	if x != nil {
		return x.TemporaryDirectory
	}
	return ""
}

func (x *RunRequest) GetServerLogsDirectory() string {
	if x != nil {
		return x.ServerLogsDirectory
	}
	return ""
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int64                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	ResourceUsage []*anypb.Any           `protobuf:"bytes,2,rep,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescGZIP(), []int{2}
}

func (x *RunResponse) GetExitCode() int64 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunResponse) GetResourceUsage() []*anypb.Any {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDesc = "" +
	"\n" +
	"Fgithub.com/buildbarn/bb-remote-execution/pkg/proto/runner/runner.proto\x12\x10buildbarn.runner\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n" +
	"\x15CheckReadinessRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xe6\x03\n" +
	"\n" +
	"RunRequest\x12\x1c\n" +
	"\targuments\x18\x01 \x03(\tR\targuments\x12k\n" +
	"\x15environment_variables\x18\x02 \x03(\v26.buildbarn.runner.RunRequest.EnvironmentVariablesEntryR\x14environmentVariables\x12+\n" +
	"\x11working_directory\x18\x03 \x01(\tR\x10workingDirectory\x12\x1f\n" +
	"\vstdout_path\x18\x04 \x01(\tR\n" +
	"stdoutPath\x12\x1f\n" +
	"\vstderr_path\x18\x05 \x01(\tR\n" +
	"stderrPath\x120\n" +
	"\x14input_root_directory\x18\x06 \x01(\tR\x12inputRootDirectory\x12/\n" +
	"\x13temporary_directory\x18\a \x01(\tR\x12temporaryDirectory\x122\n" +
	"\x15server_logs_directory\x18\b \x01(\tR\x13serverLogsDirectory\x1aG\n" +
	"\x19EnvironmentVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\vRunResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x03R\bexitCode\x12;\n" +
	"\x0eresource_usage\x18\x02 \x03(\v2\x14.google.protobuf.AnyR\rresourceUsage2\x9f\x01\n" +
	"\x06Runner\x12Q\n" +
	"\x0eCheckReadiness\x12'.buildbarn.runner.CheckReadinessRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x03Run\x12\x1c.buildbarn.runner.RunRequest\x1a\x1d.buildbarn.runner.RunResponseB;Z9github.com/buildbarn/bb-remote-execution/pkg/proto/runnerb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_goTypes = []any{
	(*CheckReadinessRequest)(nil), // 0: buildbarn.runner.CheckReadinessRequest
	(*RunRequest)(nil),            // 1: buildbarn.runner.RunRequest
	(*RunResponse)(nil),           // 2: buildbarn.runner.RunResponse
	nil,                           // 3: buildbarn.runner.RunRequest.EnvironmentVariablesEntry
	(*anypb.Any)(nil),             // 4: google.protobuf.Any
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_depIdxs = []int32{
	3, // 0: buildbarn.runner.RunRequest.environment_variables:type_name -> buildbarn.runner.RunRequest.EnvironmentVariablesEntry
	4, // 1: buildbarn.runner.RunResponse.resource_usage:type_name -> google.protobuf.Any
	0, // 2: buildbarn.runner.Runner.CheckReadiness:input_type -> buildbarn.runner.CheckReadinessRequest
	1, // 3: buildbarn.runner.Runner.Run:input_type -> buildbarn.runner.RunRequest
	5, // 4: buildbarn.runner.Runner.CheckReadiness:output_type -> google.protobuf.Empty
	2, // 5: buildbarn.runner.Runner.Run:output_type -> buildbarn.runner.RunResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_init() }
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_runner_runner_proto_depIdxs = nil
}
