// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: pkg/proto/configuration/bb_noop_worker/bb_noop_worker.proto

package bb_noop_worker

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	blobstore "github.com/buildbarn/bb-storage/pkg/proto/configuration/blobstore"
	global "github.com/buildbarn/bb-storage/pkg/proto/configuration/global"
	grpc "github.com/buildbarn/bb-storage/pkg/proto/configuration/grpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationConfiguration struct {
	state                     protoimpl.MessageState             `protogen:"open.v1"`
	Global                    *global.Configuration              `protobuf:"bytes,1,opt,name=global,proto3" json:"global,omitempty"`
	BrowserUrl                string                             `protobuf:"bytes,2,opt,name=browser_url,json=browserUrl,proto3" json:"browser_url,omitempty"`
	Scheduler                 *grpc.ClientConfiguration          `protobuf:"bytes,3,opt,name=scheduler,proto3" json:"scheduler,omitempty"`
	InstanceNamePrefix        string                             `protobuf:"bytes,4,opt,name=instance_name_prefix,json=instanceNamePrefix,proto3" json:"instance_name_prefix,omitempty"`
	Platform                  *v2.Platform                       `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	WorkerId                  map[string]string                  `protobuf:"bytes,6,rep,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentAddressableStorage *blobstore.BlobAccessConfiguration `protobuf:"bytes,7,opt,name=content_addressable_storage,json=contentAddressableStorage,proto3" json:"content_addressable_storage,omitempty"`
	MaximumMessageSizeBytes   int64                              `protobuf:"varint,8,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ApplicationConfiguration) Reset() {
	*x = ApplicationConfiguration{}
	mi := &file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationConfiguration) ProtoMessage() {}

func (x *ApplicationConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationConfiguration.ProtoReflect.Descriptor instead.
func (*ApplicationConfiguration) Descriptor() ([]byte, []int) {
	return file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationConfiguration) GetGlobal() *global.Configuration {
	if x != nil {
		return x.Global
	}
	return nil
}

func (x *ApplicationConfiguration) GetBrowserUrl() string {
	if x != nil {
		return x.BrowserUrl
	}
	return ""
}

func (x *ApplicationConfiguration) GetScheduler() *grpc.ClientConfiguration {
	if x != nil {
		return x.Scheduler
	}
	return nil
}

func (x *ApplicationConfiguration) GetInstanceNamePrefix() string {
	if x != nil {
		return x.InstanceNamePrefix
	}
	return ""
}

func (x *ApplicationConfiguration) GetPlatform() *v2.Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *ApplicationConfiguration) GetWorkerId() map[string]string {
	if x != nil {
		return x.WorkerId
	}
	return nil
}

func (x *ApplicationConfiguration) GetContentAddressableStorage() *blobstore.BlobAccessConfiguration {
	if x != nil {
		return x.ContentAddressableStorage
	}
	return nil
}

func (x *ApplicationConfiguration) GetMaximumMessageSizeBytes() int64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

var File_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto protoreflect.FileDescriptor

const file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDesc = "" +
	"\n" +
	";pkg/proto/configuration/bb_noop_worker/bb_noop_worker.proto\x12&buildbarn.configuration.bb_noop_worker\x1a6build/bazel/remote/execution/v2/remote_execution.proto\x1a1pkg/proto/configuration/blobstore/blobstore.proto\x1a+pkg/proto/configuration/global/global.proto\x1a'pkg/proto/configuration/grpc/grpc.proto\"\xaf\x05\n" +
	"\x18ApplicationConfiguration\x12E\n" +
	"\x06global\x18\x01 \x01(\v2-.buildbarn.configuration.global.ConfigurationR\x06global\x12\x1f\n" +
	"\vbrowser_url\x18\x02 \x01(\tR\n" +
	"browserUrl\x12O\n" +
	"\tscheduler\x18\x03 \x01(\v21.buildbarn.configuration.grpc.ClientConfigurationR\tscheduler\x120\n" +
	"\x14instance_name_prefix\x18\x04 \x01(\tR\x12instanceNamePrefix\x12E\n" +
	"\bplatform\x18\x05 \x01(\v2).build.bazel.remote.execution.v2.PlatformR\bplatform\x12k\n" +
	"\tworker_id\x18\x06 \x03(\v2N.buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.WorkerIdEntryR\bworkerId\x12z\n" +
	"\x1bcontent_addressable_storage\x18\a \x01(\v2:.buildbarn.configuration.blobstore.BlobAccessConfigurationR\x19contentAddressableStorage\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\b \x01(\x03R\x17maximumMessageSizeBytes\x1a;\n" +
	"\rWorkerIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01BQZOgithub.com/buildbarn/bb-remote-execution/pkg/proto/configuration/bb_noop_workerb\x06proto3"

var (
	file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDescOnce sync.Once
	file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDescData []byte
)

func file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDescGZIP() []byte {
	file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDescOnce.Do(func() {
		file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDesc), len(file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDesc)))
	})
	return file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDescData
}

var file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_goTypes = []any{
	(*ApplicationConfiguration)(nil),          // 0: buildbarn.configuration.bb_noop_worker.ApplicationConfiguration
	nil,                                       // 1: buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.WorkerIdEntry
	(*global.Configuration)(nil),              // 2: buildbarn.configuration.global.Configuration
	(*grpc.ClientConfiguration)(nil),          // 3: buildbarn.configuration.grpc.ClientConfiguration
	(*v2.Platform)(nil),                       // 4: build.bazel.remote.execution.v2.Platform
	(*blobstore.BlobAccessConfiguration)(nil), // 5: buildbarn.configuration.blobstore.BlobAccessConfiguration
}
var file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_depIdxs = []int32{
	2, // 0: buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.global:type_name -> buildbarn.configuration.global.Configuration
	3, // 1: buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.scheduler:type_name -> buildbarn.configuration.grpc.ClientConfiguration
	4, // 2: buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.platform:type_name -> build.bazel.remote.execution.v2.Platform
	1, // 3: buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.worker_id:type_name -> buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.WorkerIdEntry
	5, // 4: buildbarn.configuration.bb_noop_worker.ApplicationConfiguration.content_addressable_storage:type_name -> buildbarn.configuration.blobstore.BlobAccessConfiguration
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_init() }
func file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_init() {
	if File_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDesc), len(file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_goTypes,
		DependencyIndexes: file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_depIdxs,
		MessageInfos:      file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_msgTypes,
	}.Build()
	File_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto = out.File
	file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_goTypes = nil
	file_pkg_proto_configuration_bb_noop_worker_bb_noop_worker_proto_depIdxs = nil
}
