// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/remoteactionrouter/remoteactionrouter.proto

package remoteactionrouter

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteActionRequest struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	InstanceName    string                  `protobuf:"bytes,1,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	DigestFunction  v2.DigestFunction_Value `protobuf:"varint,2,opt,name=digest_function,json=digestFunction,proto3,enum=build.bazel.remote.execution.v2.DigestFunction_Value" json:"digest_function,omitempty"`
	Action          *v2.Action              `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	RequestMetadata *v2.RequestMetadata     `protobuf:"bytes,4,opt,name=request_metadata,json=requestMetadata,proto3" json:"request_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RouteActionRequest) Reset() {
	*x = RouteActionRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteActionRequest) ProtoMessage() {}

func (x *RouteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteActionRequest.ProtoReflect.Descriptor instead.
func (*RouteActionRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescGZIP(), []int{0}
}

func (x *RouteActionRequest) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *RouteActionRequest) GetDigestFunction() v2.DigestFunction_Value {
	if x != nil {
		return x.DigestFunction
	}
	return v2.DigestFunction_Value(0)
}

func (x *RouteActionRequest) GetAction() *v2.Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RouteActionRequest) GetRequestMetadata() *v2.RequestMetadata {
	if x != nil {
		return x.RequestMetadata
	}
	return nil
}

type RouteActionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         *v2.Action             `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	InvocationKeys []*anypb.Any           `protobuf:"bytes,4,rep,name=invocation_keys,json=invocationKeys,proto3" json:"invocation_keys,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteActionResponse) Reset() {
	*x = RouteActionResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteActionResponse) ProtoMessage() {}

func (x *RouteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteActionResponse.ProtoReflect.Descriptor instead.
func (*RouteActionResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescGZIP(), []int{1}
}

func (x *RouteActionResponse) GetAction() *v2.Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *RouteActionResponse) GetInvocationKeys() []*anypb.Any {
	if x != nil {
		return x.InvocationKeys
	}
	return nil
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDesc = "" +
	"\n" +
	"^github.com/buildbarn/bb-remote-execution/pkg/proto/remoteactionrouter/remoteactionrouter.proto\x12\x1cbuildbarn.remoteactionrouter\x1a6build/bazel/remote/execution/v2/remote_execution.proto\x1a\x19google/protobuf/any.proto\"\xb7\x02\n" +
	"\x12RouteActionRequest\x12#\n" +
	"\rinstance_name\x18\x01 \x01(\tR\finstanceName\x12^\n" +
	"\x0fdigest_function\x18\x02 \x01(\x0e25.build.bazel.remote.execution.v2.DigestFunction.ValueR\x0edigestFunction\x12?\n" +
	"\x06action\x18\x03 \x01(\v2'.build.bazel.remote.execution.v2.ActionR\x06action\x12[\n" +
	"\x10request_metadata\x18\x04 \x01(\v20.build.bazel.remote.execution.v2.RequestMetadataR\x0frequestMetadata\"\x95\x01\n" +
	"\x13RouteActionResponse\x12?\n" +
	"\x06action\x18\x01 \x01(\v2'.build.bazel.remote.execution.v2.ActionR\x06action\x12=\n" +
	"\x0finvocation_keys\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\x0einvocationKeys2\x82\x01\n" +
	"\fActionRouter\x12r\n" +
	"\vRouteAction\x120.buildbarn.remoteactionrouter.RouteActionRequest\x1a1.buildbarn.remoteactionrouter.RouteActionResponseBGZEgithub.com/buildbarn/bb-remote-execution/pkg/proto/remoteactionrouterb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_goTypes = []any{
	(*RouteActionRequest)(nil),   // 0: buildbarn.remoteactionrouter.RouteActionRequest
	(*RouteActionResponse)(nil),  // 1: buildbarn.remoteactionrouter.RouteActionResponse
	(v2.DigestFunction_Value)(0), // 2: build.bazel.remote.execution.v2.DigestFunction.Value
	(*v2.Action)(nil),            // 3: build.bazel.remote.execution.v2.Action
	(*v2.RequestMetadata)(nil),   // 4: build.bazel.remote.execution.v2.RequestMetadata
	(*anypb.Any)(nil),            // 5: google.protobuf.Any
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_depIdxs = []int32{
	2, // 0: buildbarn.remoteactionrouter.RouteActionRequest.digest_function:type_name -> build.bazel.remote.execution.v2.DigestFunction.Value
	3, // 1: buildbarn.remoteactionrouter.RouteActionRequest.action:type_name -> build.bazel.remote.execution.v2.Action
	4, // 2: buildbarn.remoteactionrouter.RouteActionRequest.request_metadata:type_name -> build.bazel.remote.execution.v2.RequestMetadata
	3, // 3: buildbarn.remoteactionrouter.RouteActionResponse.action:type_name -> build.bazel.remote.execution.v2.Action
	5, // 4: buildbarn.remoteactionrouter.RouteActionResponse.invocation_keys:type_name -> google.protobuf.Any
	0, // 5: buildbarn.remoteactionrouter.ActionRouter.RouteAction:input_type -> buildbarn.remoteactionrouter.RouteActionRequest
	1, // 6: buildbarn.remoteactionrouter.ActionRouter.RouteAction:output_type -> buildbarn.remoteactionrouter.RouteActionResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_remoteactionrouter_remoteactionrouter_proto_depIdxs = nil
}
