load("@rules_jsonnet//jsonnet:jsonnet.bzl", "jsonnet_to_json")

jsonnet_to_json(
    name = "github_workflows",
    src = "github_workflows.jsonnet",
    out_dir = "outputs",
    visibility = ["//:__pkg__"],
    deps = ["@com_github_buildbarn_bb_storage//tools/github_workflows:workflows_template"],
)
