// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/resourceusage/resourceusage.proto

package resourceusage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilePoolResourceUsage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FilesCreated       uint64                 `protobuf:"varint,1,opt,name=files_created,json=filesCreated,proto3" json:"files_created,omitempty"`
	FilesCountPeak     uint64                 `protobuf:"varint,2,opt,name=files_count_peak,json=filesCountPeak,proto3" json:"files_count_peak,omitempty"`
	FilesSizeBytesPeak uint64                 `protobuf:"varint,3,opt,name=files_size_bytes_peak,json=filesSizeBytesPeak,proto3" json:"files_size_bytes_peak,omitempty"`
	ReadsCount         uint64                 `protobuf:"varint,4,opt,name=reads_count,json=readsCount,proto3" json:"reads_count,omitempty"`
	ReadsSizeBytes     uint64                 `protobuf:"varint,5,opt,name=reads_size_bytes,json=readsSizeBytes,proto3" json:"reads_size_bytes,omitempty"`
	WritesCount        uint64                 `protobuf:"varint,6,opt,name=writes_count,json=writesCount,proto3" json:"writes_count,omitempty"`
	WritesSizeBytes    uint64                 `protobuf:"varint,7,opt,name=writes_size_bytes,json=writesSizeBytes,proto3" json:"writes_size_bytes,omitempty"`
	TruncatesCount     uint64                 `protobuf:"varint,8,opt,name=truncates_count,json=truncatesCount,proto3" json:"truncates_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FilePoolResourceUsage) Reset() {
	*x = FilePoolResourceUsage{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePoolResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePoolResourceUsage) ProtoMessage() {}

func (x *FilePoolResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePoolResourceUsage.ProtoReflect.Descriptor instead.
func (*FilePoolResourceUsage) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescGZIP(), []int{0}
}

func (x *FilePoolResourceUsage) GetFilesCreated() uint64 {
	if x != nil {
		return x.FilesCreated
	}
	return 0
}

func (x *FilePoolResourceUsage) GetFilesCountPeak() uint64 {
	if x != nil {
		return x.FilesCountPeak
	}
	return 0
}

func (x *FilePoolResourceUsage) GetFilesSizeBytesPeak() uint64 {
	if x != nil {
		return x.FilesSizeBytesPeak
	}
	return 0
}

func (x *FilePoolResourceUsage) GetReadsCount() uint64 {
	if x != nil {
		return x.ReadsCount
	}
	return 0
}

func (x *FilePoolResourceUsage) GetReadsSizeBytes() uint64 {
	if x != nil {
		return x.ReadsSizeBytes
	}
	return 0
}

func (x *FilePoolResourceUsage) GetWritesCount() uint64 {
	if x != nil {
		return x.WritesCount
	}
	return 0
}

func (x *FilePoolResourceUsage) GetWritesSizeBytes() uint64 {
	if x != nil {
		return x.WritesSizeBytes
	}
	return 0
}

func (x *FilePoolResourceUsage) GetTruncatesCount() uint64 {
	if x != nil {
		return x.TruncatesCount
	}
	return 0
}

type POSIXResourceUsage struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	UserTime                   *durationpb.Duration   `protobuf:"bytes,1,opt,name=user_time,json=userTime,proto3" json:"user_time,omitempty"`
	SystemTime                 *durationpb.Duration   `protobuf:"bytes,2,opt,name=system_time,json=systemTime,proto3" json:"system_time,omitempty"`
	MaximumResidentSetSize     int64                  `protobuf:"varint,3,opt,name=maximum_resident_set_size,json=maximumResidentSetSize,proto3" json:"maximum_resident_set_size,omitempty"`
	PageReclaims               int64                  `protobuf:"varint,7,opt,name=page_reclaims,json=pageReclaims,proto3" json:"page_reclaims,omitempty"`
	PageFaults                 int64                  `protobuf:"varint,8,opt,name=page_faults,json=pageFaults,proto3" json:"page_faults,omitempty"`
	Swaps                      int64                  `protobuf:"varint,9,opt,name=swaps,proto3" json:"swaps,omitempty"`
	BlockInputOperations       int64                  `protobuf:"varint,10,opt,name=block_input_operations,json=blockInputOperations,proto3" json:"block_input_operations,omitempty"`
	BlockOutputOperations      int64                  `protobuf:"varint,11,opt,name=block_output_operations,json=blockOutputOperations,proto3" json:"block_output_operations,omitempty"`
	MessagesSent               int64                  `protobuf:"varint,12,opt,name=messages_sent,json=messagesSent,proto3" json:"messages_sent,omitempty"`
	MessagesReceived           int64                  `protobuf:"varint,13,opt,name=messages_received,json=messagesReceived,proto3" json:"messages_received,omitempty"`
	SignalsReceived            int64                  `protobuf:"varint,14,opt,name=signals_received,json=signalsReceived,proto3" json:"signals_received,omitempty"`
	VoluntaryContextSwitches   int64                  `protobuf:"varint,15,opt,name=voluntary_context_switches,json=voluntaryContextSwitches,proto3" json:"voluntary_context_switches,omitempty"`
	InvoluntaryContextSwitches int64                  `protobuf:"varint,16,opt,name=involuntary_context_switches,json=involuntaryContextSwitches,proto3" json:"involuntary_context_switches,omitempty"`
	TerminationSignal          string                 `protobuf:"bytes,17,opt,name=termination_signal,json=terminationSignal,proto3" json:"termination_signal,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *POSIXResourceUsage) Reset() {
	*x = POSIXResourceUsage{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *POSIXResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POSIXResourceUsage) ProtoMessage() {}

func (x *POSIXResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POSIXResourceUsage.ProtoReflect.Descriptor instead.
func (*POSIXResourceUsage) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescGZIP(), []int{1}
}

func (x *POSIXResourceUsage) GetUserTime() *durationpb.Duration {
	if x != nil {
		return x.UserTime
	}
	return nil
}

func (x *POSIXResourceUsage) GetSystemTime() *durationpb.Duration {
	if x != nil {
		return x.SystemTime
	}
	return nil
}

func (x *POSIXResourceUsage) GetMaximumResidentSetSize() int64 {
	if x != nil {
		return x.MaximumResidentSetSize
	}
	return 0
}

func (x *POSIXResourceUsage) GetPageReclaims() int64 {
	if x != nil {
		return x.PageReclaims
	}
	return 0
}

func (x *POSIXResourceUsage) GetPageFaults() int64 {
	if x != nil {
		return x.PageFaults
	}
	return 0
}

func (x *POSIXResourceUsage) GetSwaps() int64 {
	if x != nil {
		return x.Swaps
	}
	return 0
}

func (x *POSIXResourceUsage) GetBlockInputOperations() int64 {
	if x != nil {
		return x.BlockInputOperations
	}
	return 0
}

func (x *POSIXResourceUsage) GetBlockOutputOperations() int64 {
	if x != nil {
		return x.BlockOutputOperations
	}
	return 0
}

func (x *POSIXResourceUsage) GetMessagesSent() int64 {
	if x != nil {
		return x.MessagesSent
	}
	return 0
}

func (x *POSIXResourceUsage) GetMessagesReceived() int64 {
	if x != nil {
		return x.MessagesReceived
	}
	return 0
}

func (x *POSIXResourceUsage) GetSignalsReceived() int64 {
	if x != nil {
		return x.SignalsReceived
	}
	return 0
}

func (x *POSIXResourceUsage) GetVoluntaryContextSwitches() int64 {
	if x != nil {
		return x.VoluntaryContextSwitches
	}
	return 0
}

func (x *POSIXResourceUsage) GetInvoluntaryContextSwitches() int64 {
	if x != nil {
		return x.InvoluntaryContextSwitches
	}
	return 0
}

func (x *POSIXResourceUsage) GetTerminationSignal() string {
	if x != nil {
		return x.TerminationSignal
	}
	return ""
}

type MonetaryResourceUsage struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Expenses      map[string]*MonetaryResourceUsage_Expense `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonetaryResourceUsage) Reset() {
	*x = MonetaryResourceUsage{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonetaryResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonetaryResourceUsage) ProtoMessage() {}

func (x *MonetaryResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonetaryResourceUsage.ProtoReflect.Descriptor instead.
func (*MonetaryResourceUsage) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescGZIP(), []int{2}
}

func (x *MonetaryResourceUsage) GetExpenses() map[string]*MonetaryResourceUsage_Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

type InputRootResourceUsage struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DirectoriesResolved uint64                 `protobuf:"varint,1,opt,name=directories_resolved,json=directoriesResolved,proto3" json:"directories_resolved,omitempty"`
	DirectoriesRead     uint64                 `protobuf:"varint,2,opt,name=directories_read,json=directoriesRead,proto3" json:"directories_read,omitempty"`
	FilesRead           uint64                 `protobuf:"varint,3,opt,name=files_read,json=filesRead,proto3" json:"files_read,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InputRootResourceUsage) Reset() {
	*x = InputRootResourceUsage{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRootResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRootResourceUsage) ProtoMessage() {}

func (x *InputRootResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRootResourceUsage.ProtoReflect.Descriptor instead.
func (*InputRootResourceUsage) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescGZIP(), []int{3}
}

func (x *InputRootResourceUsage) GetDirectoriesResolved() uint64 {
	if x != nil {
		return x.DirectoriesResolved
	}
	return 0
}

func (x *InputRootResourceUsage) GetDirectoriesRead() uint64 {
	if x != nil {
		return x.DirectoriesRead
	}
	return 0
}

func (x *InputRootResourceUsage) GetFilesRead() uint64 {
	if x != nil {
		return x.FilesRead
	}
	return 0
}

type MonetaryResourceUsage_Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Cost          float64                `protobuf:"fixed64,2,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonetaryResourceUsage_Expense) Reset() {
	*x = MonetaryResourceUsage_Expense{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonetaryResourceUsage_Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonetaryResourceUsage_Expense) ProtoMessage() {}

func (x *MonetaryResourceUsage_Expense) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonetaryResourceUsage_Expense.ProtoReflect.Descriptor instead.
func (*MonetaryResourceUsage_Expense) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescGZIP(), []int{2, 0}
}

func (x *MonetaryResourceUsage_Expense) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MonetaryResourceUsage_Expense) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDesc = "" +
	"\n" +
	"Tgithub.com/buildbarn/bb-remote-execution/pkg/proto/resourceusage/resourceusage.proto\x12\x17buildbarn.resourceusage\x1a\x1egoogle/protobuf/duration.proto\"\xdc\x02\n" +
	"\x15FilePoolResourceUsage\x12#\n" +
	"\rfiles_created\x18\x01 \x01(\x04R\ffilesCreated\x12(\n" +
	"\x10files_count_peak\x18\x02 \x01(\x04R\x0efilesCountPeak\x121\n" +
	"\x15files_size_bytes_peak\x18\x03 \x01(\x04R\x12filesSizeBytesPeak\x12\x1f\n" +
	"\vreads_count\x18\x04 \x01(\x04R\n" +
	"readsCount\x12(\n" +
	"\x10reads_size_bytes\x18\x05 \x01(\x04R\x0ereadsSizeBytes\x12!\n" +
	"\fwrites_count\x18\x06 \x01(\x04R\vwritesCount\x12*\n" +
	"\x11writes_size_bytes\x18\a \x01(\x04R\x0fwritesSizeBytes\x12'\n" +
	"\x0ftruncates_count\x18\b \x01(\x04R\x0etruncatesCount\"\xcb\x05\n" +
	"\x12POSIXResourceUsage\x126\n" +
	"\tuser_time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\buserTime\x12:\n" +
	"\vsystem_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"systemTime\x129\n" +
	"\x19maximum_resident_set_size\x18\x03 \x01(\x03R\x16maximumResidentSetSize\x12#\n" +
	"\rpage_reclaims\x18\a \x01(\x03R\fpageReclaims\x12\x1f\n" +
	"\vpage_faults\x18\b \x01(\x03R\n" +
	"pageFaults\x12\x14\n" +
	"\x05swaps\x18\t \x01(\x03R\x05swaps\x124\n" +
	"\x16block_input_operations\x18\n" +
	" \x01(\x03R\x14blockInputOperations\x126\n" +
	"\x17block_output_operations\x18\v \x01(\x03R\x15blockOutputOperations\x12#\n" +
	"\rmessages_sent\x18\f \x01(\x03R\fmessagesSent\x12+\n" +
	"\x11messages_received\x18\r \x01(\x03R\x10messagesReceived\x12)\n" +
	"\x10signals_received\x18\x0e \x01(\x03R\x0fsignalsReceived\x12<\n" +
	"\x1avoluntary_context_switches\x18\x0f \x01(\x03R\x18voluntaryContextSwitches\x12@\n" +
	"\x1cinvoluntary_context_switches\x18\x10 \x01(\x03R\x1ainvoluntaryContextSwitches\x12-\n" +
	"\x12termination_signal\x18\x11 \x01(\tR\x11terminationSignalJ\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\xa1\x02\n" +
	"\x15MonetaryResourceUsage\x12X\n" +
	"\bexpenses\x18\x01 \x03(\v2<.buildbarn.resourceusage.MonetaryResourceUsage.ExpensesEntryR\bexpenses\x1a9\n" +
	"\aExpense\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04cost\x18\x02 \x01(\x01R\x04cost\x1as\n" +
	"\rExpensesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12L\n" +
	"\x05value\x18\x02 \x01(\v26.buildbarn.resourceusage.MonetaryResourceUsage.ExpenseR\x05value:\x028\x01\"\x95\x01\n" +
	"\x16InputRootResourceUsage\x121\n" +
	"\x14directories_resolved\x18\x01 \x01(\x04R\x13directoriesResolved\x12)\n" +
	"\x10directories_read\x18\x02 \x01(\x04R\x0fdirectoriesRead\x12\x1d\n" +
	"\n" +
	"files_read\x18\x03 \x01(\x04R\tfilesReadBBZ@github.com/buildbarn/bb-remote-execution/pkg/proto/resourceusageb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_goTypes = []any{
	(*FilePoolResourceUsage)(nil),         // 0: buildbarn.resourceusage.FilePoolResourceUsage
	(*POSIXResourceUsage)(nil),            // 1: buildbarn.resourceusage.POSIXResourceUsage
	(*MonetaryResourceUsage)(nil),         // 2: buildbarn.resourceusage.MonetaryResourceUsage
	(*InputRootResourceUsage)(nil),        // 3: buildbarn.resourceusage.InputRootResourceUsage
	(*MonetaryResourceUsage_Expense)(nil), // 4: buildbarn.resourceusage.MonetaryResourceUsage.Expense
	nil,                                   // 5: buildbarn.resourceusage.MonetaryResourceUsage.ExpensesEntry
	(*durationpb.Duration)(nil),           // 6: google.protobuf.Duration
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_depIdxs = []int32{
	6, // 0: buildbarn.resourceusage.POSIXResourceUsage.user_time:type_name -> google.protobuf.Duration
	6, // 1: buildbarn.resourceusage.POSIXResourceUsage.system_time:type_name -> google.protobuf.Duration
	5, // 2: buildbarn.resourceusage.MonetaryResourceUsage.expenses:type_name -> buildbarn.resourceusage.MonetaryResourceUsage.ExpensesEntry
	4, // 3: buildbarn.resourceusage.MonetaryResourceUsage.ExpensesEntry.value:type_name -> buildbarn.resourceusage.MonetaryResourceUsage.Expense
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_resourceusage_resourceusage_proto_depIdxs = nil
}
