// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.28.1
// source: pkg/proto/bazeloutputservice/bazel_output_service.proto

package bazeloutputservice

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CleanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutputBaseId string `protobuf:"bytes,1,opt,name=output_base_id,json=outputBaseId,proto3" json:"output_base_id,omitempty"`
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{0}
}

func (x *CleanRequest) GetOutputBaseId() string {
	if x != nil {
		return x.OutputBaseId
	}
	return ""
}

type CleanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CleanResponse) Reset() {
	*x = CleanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanResponse) ProtoMessage() {}

func (x *CleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanResponse.ProtoReflect.Descriptor instead.
func (*CleanResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{1}
}

type StartBuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version           int32             `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	OutputBaseId      string            `protobuf:"bytes,2,opt,name=output_base_id,json=outputBaseId,proto3" json:"output_base_id,omitempty"`
	BuildId           string            `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Args              *anypb.Any        `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	OutputPathPrefix  string            `protobuf:"bytes,5,opt,name=output_path_prefix,json=outputPathPrefix,proto3" json:"output_path_prefix,omitempty"`
	OutputPathAliases map[string]string `protobuf:"bytes,6,rep,name=output_path_aliases,json=outputPathAliases,proto3" json:"output_path_aliases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StartBuildRequest) Reset() {
	*x = StartBuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildRequest) ProtoMessage() {}

func (x *StartBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildRequest.ProtoReflect.Descriptor instead.
func (*StartBuildRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{2}
}

func (x *StartBuildRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StartBuildRequest) GetOutputBaseId() string {
	if x != nil {
		return x.OutputBaseId
	}
	return ""
}

func (x *StartBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *StartBuildRequest) GetArgs() *anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StartBuildRequest) GetOutputPathPrefix() string {
	if x != nil {
		return x.OutputPathPrefix
	}
	return ""
}

func (x *StartBuildRequest) GetOutputPathAliases() map[string]string {
	if x != nil {
		return x.OutputPathAliases
	}
	return nil
}

type StartBuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitialOutputPathContents *InitialOutputPathContents `protobuf:"bytes,1,opt,name=initial_output_path_contents,json=initialOutputPathContents,proto3" json:"initial_output_path_contents,omitempty"`
	OutputPathSuffix          string                     `protobuf:"bytes,2,opt,name=output_path_suffix,json=outputPathSuffix,proto3" json:"output_path_suffix,omitempty"`
}

func (x *StartBuildResponse) Reset() {
	*x = StartBuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildResponse) ProtoMessage() {}

func (x *StartBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildResponse.ProtoReflect.Descriptor instead.
func (*StartBuildResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{3}
}

func (x *StartBuildResponse) GetInitialOutputPathContents() *InitialOutputPathContents {
	if x != nil {
		return x.InitialOutputPathContents
	}
	return nil
}

func (x *StartBuildResponse) GetOutputPathSuffix() string {
	if x != nil {
		return x.OutputPathSuffix
	}
	return ""
}

type InitialOutputPathContents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId              string   `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ModifiedPathPrefixes []string `protobuf:"bytes,2,rep,name=modified_path_prefixes,json=modifiedPathPrefixes,proto3" json:"modified_path_prefixes,omitempty"`
}

func (x *InitialOutputPathContents) Reset() {
	*x = InitialOutputPathContents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitialOutputPathContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialOutputPathContents) ProtoMessage() {}

func (x *InitialOutputPathContents) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialOutputPathContents.ProtoReflect.Descriptor instead.
func (*InitialOutputPathContents) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{4}
}

func (x *InitialOutputPathContents) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *InitialOutputPathContents) GetModifiedPathPrefixes() []string {
	if x != nil {
		return x.ModifiedPathPrefixes
	}
	return nil
}

type StageArtifactsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId   string                            `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Artifacts []*StageArtifactsRequest_Artifact `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
}

func (x *StageArtifactsRequest) Reset() {
	*x = StageArtifactsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsRequest) ProtoMessage() {}

func (x *StageArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsRequest.ProtoReflect.Descriptor instead.
func (*StageArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{5}
}

func (x *StageArtifactsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *StageArtifactsRequest) GetArtifacts() []*StageArtifactsRequest_Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type StageArtifactsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*StageArtifactsResponse_Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *StageArtifactsResponse) Reset() {
	*x = StageArtifactsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsResponse) ProtoMessage() {}

func (x *StageArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsResponse.ProtoReflect.Descriptor instead.
func (*StageArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{6}
}

func (x *StageArtifactsResponse) GetResponses() []*StageArtifactsResponse_Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

type FinalizeArtifactsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId   string                               `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Artifacts []*FinalizeArtifactsRequest_Artifact `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
}

func (x *FinalizeArtifactsRequest) Reset() {
	*x = FinalizeArtifactsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeArtifactsRequest) ProtoMessage() {}

func (x *FinalizeArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeArtifactsRequest.ProtoReflect.Descriptor instead.
func (*FinalizeArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{7}
}

func (x *FinalizeArtifactsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *FinalizeArtifactsRequest) GetArtifacts() []*FinalizeArtifactsRequest_Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type FinalizeArtifactsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinalizeArtifactsResponse) Reset() {
	*x = FinalizeArtifactsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeArtifactsResponse) ProtoMessage() {}

func (x *FinalizeArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeArtifactsResponse.ProtoReflect.Descriptor instead.
func (*FinalizeArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{8}
}

type FinalizeBuildRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId         string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	BuildSuccessful bool   `protobuf:"varint,2,opt,name=build_successful,json=buildSuccessful,proto3" json:"build_successful,omitempty"`
}

func (x *FinalizeBuildRequest) Reset() {
	*x = FinalizeBuildRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeBuildRequest) ProtoMessage() {}

func (x *FinalizeBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeBuildRequest.ProtoReflect.Descriptor instead.
func (*FinalizeBuildRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{9}
}

func (x *FinalizeBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *FinalizeBuildRequest) GetBuildSuccessful() bool {
	if x != nil {
		return x.BuildSuccessful
	}
	return false
}

type FinalizeBuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinalizeBuildResponse) Reset() {
	*x = FinalizeBuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeBuildResponse) ProtoMessage() {}

func (x *FinalizeBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeBuildResponse.ProtoReflect.Descriptor instead.
func (*FinalizeBuildResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{10}
}

type BatchStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuildId string   `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Paths   []string `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *BatchStatRequest) Reset() {
	*x = BatchStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatRequest) ProtoMessage() {}

func (x *BatchStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatRequest.ProtoReflect.Descriptor instead.
func (*BatchStatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{11}
}

func (x *BatchStatRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BatchStatRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type BatchStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*BatchStatResponse_StatResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
}

func (x *BatchStatResponse) Reset() {
	*x = BatchStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse) ProtoMessage() {}

func (x *BatchStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse.ProtoReflect.Descriptor instead.
func (*BatchStatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12}
}

func (x *BatchStatResponse) GetResponses() []*BatchStatResponse_StatResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type StageArtifactsRequest_Artifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Locator *anypb.Any `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
}

func (x *StageArtifactsRequest_Artifact) Reset() {
	*x = StageArtifactsRequest_Artifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageArtifactsRequest_Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsRequest_Artifact) ProtoMessage() {}

func (x *StageArtifactsRequest_Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsRequest_Artifact.ProtoReflect.Descriptor instead.
func (*StageArtifactsRequest_Artifact) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{5, 0}
}

func (x *StageArtifactsRequest_Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StageArtifactsRequest_Artifact) GetLocator() *anypb.Any {
	if x != nil {
		return x.Locator
	}
	return nil
}

type StageArtifactsResponse_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *StageArtifactsResponse_Response) Reset() {
	*x = StageArtifactsResponse_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StageArtifactsResponse_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsResponse_Response) ProtoMessage() {}

func (x *StageArtifactsResponse_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsResponse_Response.ProtoReflect.Descriptor instead.
func (*StageArtifactsResponse_Response) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *StageArtifactsResponse_Response) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type FinalizeArtifactsRequest_Artifact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Locator *anypb.Any `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
}

func (x *FinalizeArtifactsRequest_Artifact) Reset() {
	*x = FinalizeArtifactsRequest_Artifact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinalizeArtifactsRequest_Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeArtifactsRequest_Artifact) ProtoMessage() {}

func (x *FinalizeArtifactsRequest_Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeArtifactsRequest_Artifact.ProtoReflect.Descriptor instead.
func (*FinalizeArtifactsRequest_Artifact) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *FinalizeArtifactsRequest_Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FinalizeArtifactsRequest_Artifact) GetLocator() *anypb.Any {
	if x != nil {
		return x.Locator
	}
	return nil
}

type BatchStatResponse_StatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stat *BatchStatResponse_Stat `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
}

func (x *BatchStatResponse_StatResponse) Reset() {
	*x = BatchStatResponse_StatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStatResponse_StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_StatResponse) ProtoMessage() {}

func (x *BatchStatResponse_StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_StatResponse.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_StatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 0}
}

func (x *BatchStatResponse_StatResponse) GetStat() *BatchStatResponse_Stat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type BatchStatResponse_Stat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Type:
	//
	//	*BatchStatResponse_Stat_File_
	//	*BatchStatResponse_Stat_Symlink_
	//	*BatchStatResponse_Stat_Directory_
	Type isBatchStatResponse_Stat_Type `protobuf_oneof:"type"`
}

func (x *BatchStatResponse_Stat) Reset() {
	*x = BatchStatResponse_Stat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStatResponse_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat) ProtoMessage() {}

func (x *BatchStatResponse_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1}
}

func (m *BatchStatResponse_Stat) GetType() isBatchStatResponse_Stat_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *BatchStatResponse_Stat) GetFile() *BatchStatResponse_Stat_File {
	if x, ok := x.GetType().(*BatchStatResponse_Stat_File_); ok {
		return x.File
	}
	return nil
}

func (x *BatchStatResponse_Stat) GetSymlink() *BatchStatResponse_Stat_Symlink {
	if x, ok := x.GetType().(*BatchStatResponse_Stat_Symlink_); ok {
		return x.Symlink
	}
	return nil
}

func (x *BatchStatResponse_Stat) GetDirectory() *BatchStatResponse_Stat_Directory {
	if x, ok := x.GetType().(*BatchStatResponse_Stat_Directory_); ok {
		return x.Directory
	}
	return nil
}

type isBatchStatResponse_Stat_Type interface {
	isBatchStatResponse_Stat_Type()
}

type BatchStatResponse_Stat_File_ struct {
	File *BatchStatResponse_Stat_File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type BatchStatResponse_Stat_Symlink_ struct {
	Symlink *BatchStatResponse_Stat_Symlink `protobuf:"bytes,2,opt,name=symlink,proto3,oneof"`
}

type BatchStatResponse_Stat_Directory_ struct {
	Directory *BatchStatResponse_Stat_Directory `protobuf:"bytes,3,opt,name=directory,proto3,oneof"`
}

func (*BatchStatResponse_Stat_File_) isBatchStatResponse_Stat_Type() {}

func (*BatchStatResponse_Stat_Symlink_) isBatchStatResponse_Stat_Type() {}

func (*BatchStatResponse_Stat_Directory_) isBatchStatResponse_Stat_Type() {}

type BatchStatResponse_Stat_File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Locator *anypb.Any `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
}

func (x *BatchStatResponse_Stat_File) Reset() {
	*x = BatchStatResponse_Stat_File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStatResponse_Stat_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat_File) ProtoMessage() {}

func (x *BatchStatResponse_Stat_File) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat_File.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat_File) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1, 0}
}

func (x *BatchStatResponse_Stat_File) GetLocator() *anypb.Any {
	if x != nil {
		return x.Locator
	}
	return nil
}

type BatchStatResponse_Stat_Symlink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *BatchStatResponse_Stat_Symlink) Reset() {
	*x = BatchStatResponse_Stat_Symlink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStatResponse_Stat_Symlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat_Symlink) ProtoMessage() {}

func (x *BatchStatResponse_Stat_Symlink) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat_Symlink.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat_Symlink) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1, 1}
}

func (x *BatchStatResponse_Stat_Symlink) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type BatchStatResponse_Stat_Directory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BatchStatResponse_Stat_Directory) Reset() {
	*x = BatchStatResponse_Stat_Directory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchStatResponse_Stat_Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat_Directory) ProtoMessage() {}

func (x *BatchStatResponse_Stat_Directory) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat_Directory.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat_Directory) Descriptor() ([]byte, []int) {
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1, 2}
}

var File_pkg_proto_bazeloutputservice_bazel_output_service_proto protoreflect.FileDescriptor

var file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc = []byte{
	0x0a, 0x37, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x7a, 0x65,
	0x6c, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62,
	0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x62, 0x61, 0x7a, 0x65, 0x6c,
	0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a,
	0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x0c, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x6c, 0x65,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xfc, 0x02, 0x0a, 0x11, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x61, 0x73, 0x65, 0x49, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f,
	0x70, 0x61, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x74, 0x68, 0x50, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x12, 0x6e, 0x0a, 0x13, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x5f, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x3e, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x50, 0x61, 0x74, 0x68, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x11, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x74, 0x68, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x65, 0x73, 0x1a, 0x44, 0x0a, 0x16, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x74,
	0x68, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xb4, 0x01, 0x0a, 0x12, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x70, 0x0a, 0x1c, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x74, 0x68, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x19, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x70, 0x61, 0x74,
	0x68, 0x5f, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x50, 0x61, 0x74, 0x68, 0x53, 0x75, 0x66, 0x66, 0x69, 0x78,
	0x22, 0x6c, 0x0a, 0x19, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x50, 0x61, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x16, 0x6d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x14, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x50, 0x61, 0x74, 0x68, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x22, 0xd6,
	0x01, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x67, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x49, 0x64, 0x12, 0x52, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x67, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x52, 0x09, 0x61, 0x72,
	0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x1a, 0x4e, 0x0a, 0x08, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2e, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xa5, 0x01, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x53, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x1a, 0x36, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0xdc, 0x01, 0x0a, 0x18, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x74, 0x69,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x55, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x62, 0x61, 0x7a,
	0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x1a, 0x4e,
	0x0a, 0x08, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2e,
	0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x1b,
	0x0a, 0x19, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5c, 0x0a, 0x14, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x12, 0x29,
	0x0a, 0x10, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66,
	0x75, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x22, 0x17, 0x0a, 0x15, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x43, 0x0a, 0x10, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0xa5, 0x04, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x52, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x34, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x73, 0x1a, 0x50, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2c, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73,
	0x74, 0x61, 0x74, 0x1a, 0xe9, 0x02, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74, 0x12, 0x47, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x62, 0x61, 0x7a,
	0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x50, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x2e, 0x53, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x48, 0x00, 0x52, 0x07,
	0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x56, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x62, 0x61, 0x7a,
	0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x48, 0x00, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x1a,
	0x36, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x1a, 0x21, 0x0a, 0x07, 0x53, 0x79, 0x6d, 0x6c, 0x69,
	0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x0b, 0x0a, 0x09, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x32,
	0xf2, 0x04, 0x0a, 0x12, 0x42, 0x61, 0x7a, 0x65, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x05, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x12,
	0x22, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x27, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x28, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b, 0x0a, 0x0e, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x2b, 0x2e, 0x62, 0x61,
	0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x67, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c,
	0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x67, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x74, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x73, 0x12, 0x2e, 0x2e, 0x62, 0x61,
	0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x62, 0x61,
	0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x74, 0x69, 0x66,
	0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x0d,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x12, 0x2a, 0x2e,
	0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x62, 0x61, 0x7a, 0x65,
	0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x26, 0x2e, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62, 0x61,
	0x7a, 0x65, 0x6c, 0x5f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x53, 0x0a, 0x24, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x64, 0x65, 0x76, 0x74, 0x6f, 0x6f, 0x6c, 0x73, 0x2e, 0x62, 0x75, 0x69, 0x6c,
	0x64, 0x2e, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x42, 0x17, 0x42, 0x61,
	0x7a, 0x65, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x12, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x6f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescOnce sync.Once
	file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescData = file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc
)

func file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescData)
	})
	return file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescData
}

var file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_pkg_proto_bazeloutputservice_bazel_output_service_proto_goTypes = []interface{}{
	(*CleanRequest)(nil),                      // 0: bazel_output_service.CleanRequest
	(*CleanResponse)(nil),                     // 1: bazel_output_service.CleanResponse
	(*StartBuildRequest)(nil),                 // 2: bazel_output_service.StartBuildRequest
	(*StartBuildResponse)(nil),                // 3: bazel_output_service.StartBuildResponse
	(*InitialOutputPathContents)(nil),         // 4: bazel_output_service.InitialOutputPathContents
	(*StageArtifactsRequest)(nil),             // 5: bazel_output_service.StageArtifactsRequest
	(*StageArtifactsResponse)(nil),            // 6: bazel_output_service.StageArtifactsResponse
	(*FinalizeArtifactsRequest)(nil),          // 7: bazel_output_service.FinalizeArtifactsRequest
	(*FinalizeArtifactsResponse)(nil),         // 8: bazel_output_service.FinalizeArtifactsResponse
	(*FinalizeBuildRequest)(nil),              // 9: bazel_output_service.FinalizeBuildRequest
	(*FinalizeBuildResponse)(nil),             // 10: bazel_output_service.FinalizeBuildResponse
	(*BatchStatRequest)(nil),                  // 11: bazel_output_service.BatchStatRequest
	(*BatchStatResponse)(nil),                 // 12: bazel_output_service.BatchStatResponse
	nil,                                       // 13: bazel_output_service.StartBuildRequest.OutputPathAliasesEntry
	(*StageArtifactsRequest_Artifact)(nil),    // 14: bazel_output_service.StageArtifactsRequest.Artifact
	(*StageArtifactsResponse_Response)(nil),   // 15: bazel_output_service.StageArtifactsResponse.Response
	(*FinalizeArtifactsRequest_Artifact)(nil), // 16: bazel_output_service.FinalizeArtifactsRequest.Artifact
	(*BatchStatResponse_StatResponse)(nil),    // 17: bazel_output_service.BatchStatResponse.StatResponse
	(*BatchStatResponse_Stat)(nil),            // 18: bazel_output_service.BatchStatResponse.Stat
	(*BatchStatResponse_Stat_File)(nil),       // 19: bazel_output_service.BatchStatResponse.Stat.File
	(*BatchStatResponse_Stat_Symlink)(nil),    // 20: bazel_output_service.BatchStatResponse.Stat.Symlink
	(*BatchStatResponse_Stat_Directory)(nil),  // 21: bazel_output_service.BatchStatResponse.Stat.Directory
	(*anypb.Any)(nil),                         // 22: google.protobuf.Any
	(*status.Status)(nil),                     // 23: google.rpc.Status
}
var file_pkg_proto_bazeloutputservice_bazel_output_service_proto_depIdxs = []int32{
	22, // 0: bazel_output_service.StartBuildRequest.args:type_name -> google.protobuf.Any
	13, // 1: bazel_output_service.StartBuildRequest.output_path_aliases:type_name -> bazel_output_service.StartBuildRequest.OutputPathAliasesEntry
	4,  // 2: bazel_output_service.StartBuildResponse.initial_output_path_contents:type_name -> bazel_output_service.InitialOutputPathContents
	14, // 3: bazel_output_service.StageArtifactsRequest.artifacts:type_name -> bazel_output_service.StageArtifactsRequest.Artifact
	15, // 4: bazel_output_service.StageArtifactsResponse.responses:type_name -> bazel_output_service.StageArtifactsResponse.Response
	16, // 5: bazel_output_service.FinalizeArtifactsRequest.artifacts:type_name -> bazel_output_service.FinalizeArtifactsRequest.Artifact
	17, // 6: bazel_output_service.BatchStatResponse.responses:type_name -> bazel_output_service.BatchStatResponse.StatResponse
	22, // 7: bazel_output_service.StageArtifactsRequest.Artifact.locator:type_name -> google.protobuf.Any
	23, // 8: bazel_output_service.StageArtifactsResponse.Response.status:type_name -> google.rpc.Status
	22, // 9: bazel_output_service.FinalizeArtifactsRequest.Artifact.locator:type_name -> google.protobuf.Any
	18, // 10: bazel_output_service.BatchStatResponse.StatResponse.stat:type_name -> bazel_output_service.BatchStatResponse.Stat
	19, // 11: bazel_output_service.BatchStatResponse.Stat.file:type_name -> bazel_output_service.BatchStatResponse.Stat.File
	20, // 12: bazel_output_service.BatchStatResponse.Stat.symlink:type_name -> bazel_output_service.BatchStatResponse.Stat.Symlink
	21, // 13: bazel_output_service.BatchStatResponse.Stat.directory:type_name -> bazel_output_service.BatchStatResponse.Stat.Directory
	22, // 14: bazel_output_service.BatchStatResponse.Stat.File.locator:type_name -> google.protobuf.Any
	0,  // 15: bazel_output_service.BazelOutputService.Clean:input_type -> bazel_output_service.CleanRequest
	2,  // 16: bazel_output_service.BazelOutputService.StartBuild:input_type -> bazel_output_service.StartBuildRequest
	5,  // 17: bazel_output_service.BazelOutputService.StageArtifacts:input_type -> bazel_output_service.StageArtifactsRequest
	7,  // 18: bazel_output_service.BazelOutputService.FinalizeArtifacts:input_type -> bazel_output_service.FinalizeArtifactsRequest
	9,  // 19: bazel_output_service.BazelOutputService.FinalizeBuild:input_type -> bazel_output_service.FinalizeBuildRequest
	11, // 20: bazel_output_service.BazelOutputService.BatchStat:input_type -> bazel_output_service.BatchStatRequest
	1,  // 21: bazel_output_service.BazelOutputService.Clean:output_type -> bazel_output_service.CleanResponse
	3,  // 22: bazel_output_service.BazelOutputService.StartBuild:output_type -> bazel_output_service.StartBuildResponse
	6,  // 23: bazel_output_service.BazelOutputService.StageArtifacts:output_type -> bazel_output_service.StageArtifactsResponse
	8,  // 24: bazel_output_service.BazelOutputService.FinalizeArtifacts:output_type -> bazel_output_service.FinalizeArtifactsResponse
	10, // 25: bazel_output_service.BazelOutputService.FinalizeBuild:output_type -> bazel_output_service.FinalizeBuildResponse
	12, // 26: bazel_output_service.BazelOutputService.BatchStat:output_type -> bazel_output_service.BatchStatResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pkg_proto_bazeloutputservice_bazel_output_service_proto_init() }
func file_pkg_proto_bazeloutputservice_bazel_output_service_proto_init() {
	if File_pkg_proto_bazeloutputservice_bazel_output_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CleanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CleanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartBuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitialOutputPathContents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageArtifactsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageArtifactsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeArtifactsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeArtifactsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeBuildRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeBuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageArtifactsRequest_Artifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StageArtifactsResponse_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinalizeArtifactsRequest_Artifact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStatResponse_StatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStatResponse_Stat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStatResponse_Stat_File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStatResponse_Stat_Symlink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchStatResponse_Stat_Directory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[18].OneofWrappers = []interface{}{
		(*BatchStatResponse_Stat_File_)(nil),
		(*BatchStatResponse_Stat_Symlink_)(nil),
		(*BatchStatResponse_Stat_Directory_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_bazeloutputservice_bazel_output_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_bazeloutputservice_bazel_output_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_bazeloutputservice_bazel_output_service_proto = out.File
	file_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc = nil
	file_pkg_proto_bazeloutputservice_bazel_output_service_proto_goTypes = nil
	file_pkg_proto_bazeloutputservice_bazel_output_service_proto_depIdxs = nil
}
