// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/bazeloutputservice/bazel_output_service.proto

package bazeloutputservice

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CleanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputBaseId  string                 `protobuf:"bytes,1,opt,name=output_base_id,json=outputBaseId,proto3" json:"output_base_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanRequest) Reset() {
	*x = CleanRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanRequest) ProtoMessage() {}

func (x *CleanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanRequest.ProtoReflect.Descriptor instead.
func (*CleanRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{0}
}

func (x *CleanRequest) GetOutputBaseId() string {
	if x != nil {
		return x.OutputBaseId
	}
	return ""
}

type CleanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanResponse) Reset() {
	*x = CleanResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanResponse) ProtoMessage() {}

func (x *CleanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanResponse.ProtoReflect.Descriptor instead.
func (*CleanResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{1}
}

type StartBuildRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	OutputBaseId      string                 `protobuf:"bytes,2,opt,name=output_base_id,json=outputBaseId,proto3" json:"output_base_id,omitempty"`
	BuildId           string                 `protobuf:"bytes,3,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Args              *anypb.Any             `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	OutputPathPrefix  string                 `protobuf:"bytes,5,opt,name=output_path_prefix,json=outputPathPrefix,proto3" json:"output_path_prefix,omitempty"`
	OutputPathAliases map[string]string      `protobuf:"bytes,6,rep,name=output_path_aliases,json=outputPathAliases,proto3" json:"output_path_aliases,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartBuildRequest) Reset() {
	*x = StartBuildRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildRequest) ProtoMessage() {}

func (x *StartBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildRequest.ProtoReflect.Descriptor instead.
func (*StartBuildRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{2}
}

func (x *StartBuildRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StartBuildRequest) GetOutputBaseId() string {
	if x != nil {
		return x.OutputBaseId
	}
	return ""
}

func (x *StartBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *StartBuildRequest) GetArgs() *anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StartBuildRequest) GetOutputPathPrefix() string {
	if x != nil {
		return x.OutputPathPrefix
	}
	return ""
}

func (x *StartBuildRequest) GetOutputPathAliases() map[string]string {
	if x != nil {
		return x.OutputPathAliases
	}
	return nil
}

type StartBuildResponse struct {
	state                     protoimpl.MessageState     `protogen:"open.v1"`
	InitialOutputPathContents *InitialOutputPathContents `protobuf:"bytes,1,opt,name=initial_output_path_contents,json=initialOutputPathContents,proto3" json:"initial_output_path_contents,omitempty"`
	OutputPathSuffix          string                     `protobuf:"bytes,2,opt,name=output_path_suffix,json=outputPathSuffix,proto3" json:"output_path_suffix,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *StartBuildResponse) Reset() {
	*x = StartBuildResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartBuildResponse) ProtoMessage() {}

func (x *StartBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartBuildResponse.ProtoReflect.Descriptor instead.
func (*StartBuildResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{3}
}

func (x *StartBuildResponse) GetInitialOutputPathContents() *InitialOutputPathContents {
	if x != nil {
		return x.InitialOutputPathContents
	}
	return nil
}

func (x *StartBuildResponse) GetOutputPathSuffix() string {
	if x != nil {
		return x.OutputPathSuffix
	}
	return ""
}

type InitialOutputPathContents struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BuildId              string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	ModifiedPathPrefixes []string               `protobuf:"bytes,2,rep,name=modified_path_prefixes,json=modifiedPathPrefixes,proto3" json:"modified_path_prefixes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InitialOutputPathContents) Reset() {
	*x = InitialOutputPathContents{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialOutputPathContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialOutputPathContents) ProtoMessage() {}

func (x *InitialOutputPathContents) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialOutputPathContents.ProtoReflect.Descriptor instead.
func (*InitialOutputPathContents) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{4}
}

func (x *InitialOutputPathContents) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *InitialOutputPathContents) GetModifiedPathPrefixes() []string {
	if x != nil {
		return x.ModifiedPathPrefixes
	}
	return nil
}

type StageArtifactsRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	BuildId       string                            `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Artifacts     []*StageArtifactsRequest_Artifact `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageArtifactsRequest) Reset() {
	*x = StageArtifactsRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsRequest) ProtoMessage() {}

func (x *StageArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsRequest.ProtoReflect.Descriptor instead.
func (*StageArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{5}
}

func (x *StageArtifactsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *StageArtifactsRequest) GetArtifacts() []*StageArtifactsRequest_Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type StageArtifactsResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Responses     []*StageArtifactsResponse_Response `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageArtifactsResponse) Reset() {
	*x = StageArtifactsResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsResponse) ProtoMessage() {}

func (x *StageArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsResponse.ProtoReflect.Descriptor instead.
func (*StageArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{6}
}

func (x *StageArtifactsResponse) GetResponses() []*StageArtifactsResponse_Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

type FinalizeArtifactsRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	BuildId       string                               `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Artifacts     []*FinalizeArtifactsRequest_Artifact `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeArtifactsRequest) Reset() {
	*x = FinalizeArtifactsRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeArtifactsRequest) ProtoMessage() {}

func (x *FinalizeArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeArtifactsRequest.ProtoReflect.Descriptor instead.
func (*FinalizeArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{7}
}

func (x *FinalizeArtifactsRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *FinalizeArtifactsRequest) GetArtifacts() []*FinalizeArtifactsRequest_Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type FinalizeArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeArtifactsResponse) Reset() {
	*x = FinalizeArtifactsResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeArtifactsResponse) ProtoMessage() {}

func (x *FinalizeArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeArtifactsResponse.ProtoReflect.Descriptor instead.
func (*FinalizeArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{8}
}

type FinalizeBuildRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BuildId         string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	BuildSuccessful bool                   `protobuf:"varint,2,opt,name=build_successful,json=buildSuccessful,proto3" json:"build_successful,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FinalizeBuildRequest) Reset() {
	*x = FinalizeBuildRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeBuildRequest) ProtoMessage() {}

func (x *FinalizeBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeBuildRequest.ProtoReflect.Descriptor instead.
func (*FinalizeBuildRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{9}
}

func (x *FinalizeBuildRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *FinalizeBuildRequest) GetBuildSuccessful() bool {
	if x != nil {
		return x.BuildSuccessful
	}
	return false
}

type FinalizeBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeBuildResponse) Reset() {
	*x = FinalizeBuildResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeBuildResponse) ProtoMessage() {}

func (x *FinalizeBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeBuildResponse.ProtoReflect.Descriptor instead.
func (*FinalizeBuildResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{10}
}

type BatchStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Paths         []string               `protobuf:"bytes,2,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatRequest) Reset() {
	*x = BatchStatRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatRequest) ProtoMessage() {}

func (x *BatchStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatRequest.ProtoReflect.Descriptor instead.
func (*BatchStatRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{11}
}

func (x *BatchStatRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BatchStatRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type BatchStatResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Responses     []*BatchStatResponse_StatResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatResponse) Reset() {
	*x = BatchStatResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse) ProtoMessage() {}

func (x *BatchStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse.ProtoReflect.Descriptor instead.
func (*BatchStatResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12}
}

func (x *BatchStatResponse) GetResponses() []*BatchStatResponse_StatResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type StageArtifactsRequest_Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Locator       *anypb.Any             `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageArtifactsRequest_Artifact) Reset() {
	*x = StageArtifactsRequest_Artifact{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageArtifactsRequest_Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsRequest_Artifact) ProtoMessage() {}

func (x *StageArtifactsRequest_Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsRequest_Artifact.ProtoReflect.Descriptor instead.
func (*StageArtifactsRequest_Artifact) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{5, 0}
}

func (x *StageArtifactsRequest_Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StageArtifactsRequest_Artifact) GetLocator() *anypb.Any {
	if x != nil {
		return x.Locator
	}
	return nil
}

type StageArtifactsResponse_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageArtifactsResponse_Response) Reset() {
	*x = StageArtifactsResponse_Response{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageArtifactsResponse_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageArtifactsResponse_Response) ProtoMessage() {}

func (x *StageArtifactsResponse_Response) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageArtifactsResponse_Response.ProtoReflect.Descriptor instead.
func (*StageArtifactsResponse_Response) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *StageArtifactsResponse_Response) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type FinalizeArtifactsRequest_Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Locator       *anypb.Any             `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeArtifactsRequest_Artifact) Reset() {
	*x = FinalizeArtifactsRequest_Artifact{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeArtifactsRequest_Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeArtifactsRequest_Artifact) ProtoMessage() {}

func (x *FinalizeArtifactsRequest_Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeArtifactsRequest_Artifact.ProtoReflect.Descriptor instead.
func (*FinalizeArtifactsRequest_Artifact) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *FinalizeArtifactsRequest_Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FinalizeArtifactsRequest_Artifact) GetLocator() *anypb.Any {
	if x != nil {
		return x.Locator
	}
	return nil
}

type BatchStatResponse_StatResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Stat          *BatchStatResponse_Stat `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatResponse_StatResponse) Reset() {
	*x = BatchStatResponse_StatResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatResponse_StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_StatResponse) ProtoMessage() {}

func (x *BatchStatResponse_StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_StatResponse.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_StatResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 0}
}

func (x *BatchStatResponse_StatResponse) GetStat() *BatchStatResponse_Stat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type BatchStatResponse_Stat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*BatchStatResponse_Stat_File_
	//	*BatchStatResponse_Stat_Symlink_
	//	*BatchStatResponse_Stat_Directory_
	Type          isBatchStatResponse_Stat_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatResponse_Stat) Reset() {
	*x = BatchStatResponse_Stat{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatResponse_Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat) ProtoMessage() {}

func (x *BatchStatResponse_Stat) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1}
}

func (x *BatchStatResponse_Stat) GetType() isBatchStatResponse_Stat_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *BatchStatResponse_Stat) GetFile() *BatchStatResponse_Stat_File {
	if x != nil {
		if x, ok := x.Type.(*BatchStatResponse_Stat_File_); ok {
			return x.File
		}
	}
	return nil
}

func (x *BatchStatResponse_Stat) GetSymlink() *BatchStatResponse_Stat_Symlink {
	if x != nil {
		if x, ok := x.Type.(*BatchStatResponse_Stat_Symlink_); ok {
			return x.Symlink
		}
	}
	return nil
}

func (x *BatchStatResponse_Stat) GetDirectory() *BatchStatResponse_Stat_Directory {
	if x != nil {
		if x, ok := x.Type.(*BatchStatResponse_Stat_Directory_); ok {
			return x.Directory
		}
	}
	return nil
}

type isBatchStatResponse_Stat_Type interface {
	isBatchStatResponse_Stat_Type()
}

type BatchStatResponse_Stat_File_ struct {
	File *BatchStatResponse_Stat_File `protobuf:"bytes,1,opt,name=file,proto3,oneof"`
}

type BatchStatResponse_Stat_Symlink_ struct {
	Symlink *BatchStatResponse_Stat_Symlink `protobuf:"bytes,2,opt,name=symlink,proto3,oneof"`
}

type BatchStatResponse_Stat_Directory_ struct {
	Directory *BatchStatResponse_Stat_Directory `protobuf:"bytes,3,opt,name=directory,proto3,oneof"`
}

func (*BatchStatResponse_Stat_File_) isBatchStatResponse_Stat_Type() {}

func (*BatchStatResponse_Stat_Symlink_) isBatchStatResponse_Stat_Type() {}

func (*BatchStatResponse_Stat_Directory_) isBatchStatResponse_Stat_Type() {}

type BatchStatResponse_Stat_File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locator       *anypb.Any             `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatResponse_Stat_File) Reset() {
	*x = BatchStatResponse_Stat_File{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatResponse_Stat_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat_File) ProtoMessage() {}

func (x *BatchStatResponse_Stat_File) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat_File.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat_File) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1, 0}
}

func (x *BatchStatResponse_Stat_File) GetLocator() *anypb.Any {
	if x != nil {
		return x.Locator
	}
	return nil
}

type BatchStatResponse_Stat_Symlink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatResponse_Stat_Symlink) Reset() {
	*x = BatchStatResponse_Stat_Symlink{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatResponse_Stat_Symlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat_Symlink) ProtoMessage() {}

func (x *BatchStatResponse_Stat_Symlink) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat_Symlink.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat_Symlink) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1, 1}
}

func (x *BatchStatResponse_Stat_Symlink) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type BatchStatResponse_Stat_Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatResponse_Stat_Directory) Reset() {
	*x = BatchStatResponse_Stat_Directory{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatResponse_Stat_Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatResponse_Stat_Directory) ProtoMessage() {}

func (x *BatchStatResponse_Stat_Directory) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatResponse_Stat_Directory.ProtoReflect.Descriptor instead.
func (*BatchStatResponse_Stat_Directory) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP(), []int{12, 1, 2}
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc = "" +
	"\n" +
	"`github.com/buildbarn/bb-remote-execution/pkg/proto/bazeloutputservice/bazel_output_service.proto\x12\x14bazel_output_service\x1a\x19google/protobuf/any.proto\x1a\x17google/rpc/status.proto\"4\n" +
	"\fCleanRequest\x12$\n" +
	"\x0eoutput_base_id\x18\x01 \x01(\tR\foutputBaseId\"\x0f\n" +
	"\rCleanResponse\"\xfc\x02\n" +
	"\x11StartBuildRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12$\n" +
	"\x0eoutput_base_id\x18\x02 \x01(\tR\foutputBaseId\x12\x19\n" +
	"\bbuild_id\x18\x03 \x01(\tR\abuildId\x12(\n" +
	"\x04args\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x04args\x12,\n" +
	"\x12output_path_prefix\x18\x05 \x01(\tR\x10outputPathPrefix\x12n\n" +
	"\x13output_path_aliases\x18\x06 \x03(\v2>.bazel_output_service.StartBuildRequest.OutputPathAliasesEntryR\x11outputPathAliases\x1aD\n" +
	"\x16OutputPathAliasesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x01\n" +
	"\x12StartBuildResponse\x12p\n" +
	"\x1cinitial_output_path_contents\x18\x01 \x01(\v2/.bazel_output_service.InitialOutputPathContentsR\x19initialOutputPathContents\x12,\n" +
	"\x12output_path_suffix\x18\x02 \x01(\tR\x10outputPathSuffix\"l\n" +
	"\x19InitialOutputPathContents\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x124\n" +
	"\x16modified_path_prefixes\x18\x02 \x03(\tR\x14modifiedPathPrefixes\"\xd6\x01\n" +
	"\x15StageArtifactsRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12R\n" +
	"\tartifacts\x18\x02 \x03(\v24.bazel_output_service.StageArtifactsRequest.ArtifactR\tartifacts\x1aN\n" +
	"\bArtifact\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12.\n" +
	"\alocator\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\alocator\"\xa5\x01\n" +
	"\x16StageArtifactsResponse\x12S\n" +
	"\tresponses\x18\x01 \x03(\v25.bazel_output_service.StageArtifactsResponse.ResponseR\tresponses\x1a6\n" +
	"\bResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\"\xdc\x01\n" +
	"\x18FinalizeArtifactsRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12U\n" +
	"\tartifacts\x18\x02 \x03(\v27.bazel_output_service.FinalizeArtifactsRequest.ArtifactR\tartifacts\x1aN\n" +
	"\bArtifact\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12.\n" +
	"\alocator\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\alocator\"\x1b\n" +
	"\x19FinalizeArtifactsResponse\"\\\n" +
	"\x14FinalizeBuildRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12)\n" +
	"\x10build_successful\x18\x02 \x01(\bR\x0fbuildSuccessful\"\x17\n" +
	"\x15FinalizeBuildResponse\"C\n" +
	"\x10BatchStatRequest\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x14\n" +
	"\x05paths\x18\x02 \x03(\tR\x05paths\"\xa5\x04\n" +
	"\x11BatchStatResponse\x12R\n" +
	"\tresponses\x18\x01 \x03(\v24.bazel_output_service.BatchStatResponse.StatResponseR\tresponses\x1aP\n" +
	"\fStatResponse\x12@\n" +
	"\x04stat\x18\x01 \x01(\v2,.bazel_output_service.BatchStatResponse.StatR\x04stat\x1a\xe9\x02\n" +
	"\x04Stat\x12G\n" +
	"\x04file\x18\x01 \x01(\v21.bazel_output_service.BatchStatResponse.Stat.FileH\x00R\x04file\x12P\n" +
	"\asymlink\x18\x02 \x01(\v24.bazel_output_service.BatchStatResponse.Stat.SymlinkH\x00R\asymlink\x12V\n" +
	"\tdirectory\x18\x03 \x01(\v26.bazel_output_service.BatchStatResponse.Stat.DirectoryH\x00R\tdirectory\x1a6\n" +
	"\x04File\x12.\n" +
	"\alocator\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\alocator\x1a!\n" +
	"\aSymlink\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x1a\v\n" +
	"\tDirectoryB\x06\n" +
	"\x04type2\xf2\x04\n" +
	"\x12BazelOutputService\x12P\n" +
	"\x05Clean\x12\".bazel_output_service.CleanRequest\x1a#.bazel_output_service.CleanResponse\x12_\n" +
	"\n" +
	"StartBuild\x12'.bazel_output_service.StartBuildRequest\x1a(.bazel_output_service.StartBuildResponse\x12k\n" +
	"\x0eStageArtifacts\x12+.bazel_output_service.StageArtifactsRequest\x1a,.bazel_output_service.StageArtifactsResponse\x12t\n" +
	"\x11FinalizeArtifacts\x12..bazel_output_service.FinalizeArtifactsRequest\x1a/.bazel_output_service.FinalizeArtifactsResponse\x12h\n" +
	"\rFinalizeBuild\x12*.bazel_output_service.FinalizeBuildRequest\x1a+.bazel_output_service.FinalizeBuildResponse\x12\\\n" +
	"\tBatchStat\x12&.bazel_output_service.BatchStatRequest\x1a'.bazel_output_service.BatchStatResponseBS\n" +
	"$com.google.devtools.build.lib.remoteB\x17BazelOutputServiceProtoZ\x12bazeloutputserviceb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_goTypes = []any{
	(*CleanRequest)(nil),                      // 0: bazel_output_service.CleanRequest
	(*CleanResponse)(nil),                     // 1: bazel_output_service.CleanResponse
	(*StartBuildRequest)(nil),                 // 2: bazel_output_service.StartBuildRequest
	(*StartBuildResponse)(nil),                // 3: bazel_output_service.StartBuildResponse
	(*InitialOutputPathContents)(nil),         // 4: bazel_output_service.InitialOutputPathContents
	(*StageArtifactsRequest)(nil),             // 5: bazel_output_service.StageArtifactsRequest
	(*StageArtifactsResponse)(nil),            // 6: bazel_output_service.StageArtifactsResponse
	(*FinalizeArtifactsRequest)(nil),          // 7: bazel_output_service.FinalizeArtifactsRequest
	(*FinalizeArtifactsResponse)(nil),         // 8: bazel_output_service.FinalizeArtifactsResponse
	(*FinalizeBuildRequest)(nil),              // 9: bazel_output_service.FinalizeBuildRequest
	(*FinalizeBuildResponse)(nil),             // 10: bazel_output_service.FinalizeBuildResponse
	(*BatchStatRequest)(nil),                  // 11: bazel_output_service.BatchStatRequest
	(*BatchStatResponse)(nil),                 // 12: bazel_output_service.BatchStatResponse
	nil,                                       // 13: bazel_output_service.StartBuildRequest.OutputPathAliasesEntry
	(*StageArtifactsRequest_Artifact)(nil),    // 14: bazel_output_service.StageArtifactsRequest.Artifact
	(*StageArtifactsResponse_Response)(nil),   // 15: bazel_output_service.StageArtifactsResponse.Response
	(*FinalizeArtifactsRequest_Artifact)(nil), // 16: bazel_output_service.FinalizeArtifactsRequest.Artifact
	(*BatchStatResponse_StatResponse)(nil),    // 17: bazel_output_service.BatchStatResponse.StatResponse
	(*BatchStatResponse_Stat)(nil),            // 18: bazel_output_service.BatchStatResponse.Stat
	(*BatchStatResponse_Stat_File)(nil),       // 19: bazel_output_service.BatchStatResponse.Stat.File
	(*BatchStatResponse_Stat_Symlink)(nil),    // 20: bazel_output_service.BatchStatResponse.Stat.Symlink
	(*BatchStatResponse_Stat_Directory)(nil),  // 21: bazel_output_service.BatchStatResponse.Stat.Directory
	(*anypb.Any)(nil),                         // 22: google.protobuf.Any
	(*status.Status)(nil),                     // 23: google.rpc.Status
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_depIdxs = []int32{
	22, // 0: bazel_output_service.StartBuildRequest.args:type_name -> google.protobuf.Any
	13, // 1: bazel_output_service.StartBuildRequest.output_path_aliases:type_name -> bazel_output_service.StartBuildRequest.OutputPathAliasesEntry
	4,  // 2: bazel_output_service.StartBuildResponse.initial_output_path_contents:type_name -> bazel_output_service.InitialOutputPathContents
	14, // 3: bazel_output_service.StageArtifactsRequest.artifacts:type_name -> bazel_output_service.StageArtifactsRequest.Artifact
	15, // 4: bazel_output_service.StageArtifactsResponse.responses:type_name -> bazel_output_service.StageArtifactsResponse.Response
	16, // 5: bazel_output_service.FinalizeArtifactsRequest.artifacts:type_name -> bazel_output_service.FinalizeArtifactsRequest.Artifact
	17, // 6: bazel_output_service.BatchStatResponse.responses:type_name -> bazel_output_service.BatchStatResponse.StatResponse
	22, // 7: bazel_output_service.StageArtifactsRequest.Artifact.locator:type_name -> google.protobuf.Any
	23, // 8: bazel_output_service.StageArtifactsResponse.Response.status:type_name -> google.rpc.Status
	22, // 9: bazel_output_service.FinalizeArtifactsRequest.Artifact.locator:type_name -> google.protobuf.Any
	18, // 10: bazel_output_service.BatchStatResponse.StatResponse.stat:type_name -> bazel_output_service.BatchStatResponse.Stat
	19, // 11: bazel_output_service.BatchStatResponse.Stat.file:type_name -> bazel_output_service.BatchStatResponse.Stat.File
	20, // 12: bazel_output_service.BatchStatResponse.Stat.symlink:type_name -> bazel_output_service.BatchStatResponse.Stat.Symlink
	21, // 13: bazel_output_service.BatchStatResponse.Stat.directory:type_name -> bazel_output_service.BatchStatResponse.Stat.Directory
	22, // 14: bazel_output_service.BatchStatResponse.Stat.File.locator:type_name -> google.protobuf.Any
	0,  // 15: bazel_output_service.BazelOutputService.Clean:input_type -> bazel_output_service.CleanRequest
	2,  // 16: bazel_output_service.BazelOutputService.StartBuild:input_type -> bazel_output_service.StartBuildRequest
	5,  // 17: bazel_output_service.BazelOutputService.StageArtifacts:input_type -> bazel_output_service.StageArtifactsRequest
	7,  // 18: bazel_output_service.BazelOutputService.FinalizeArtifacts:input_type -> bazel_output_service.FinalizeArtifactsRequest
	9,  // 19: bazel_output_service.BazelOutputService.FinalizeBuild:input_type -> bazel_output_service.FinalizeBuildRequest
	11, // 20: bazel_output_service.BazelOutputService.BatchStat:input_type -> bazel_output_service.BatchStatRequest
	1,  // 21: bazel_output_service.BazelOutputService.Clean:output_type -> bazel_output_service.CleanResponse
	3,  // 22: bazel_output_service.BazelOutputService.StartBuild:output_type -> bazel_output_service.StartBuildResponse
	6,  // 23: bazel_output_service.BazelOutputService.StageArtifacts:output_type -> bazel_output_service.StageArtifactsResponse
	8,  // 24: bazel_output_service.BazelOutputService.FinalizeArtifacts:output_type -> bazel_output_service.FinalizeArtifactsResponse
	10, // 25: bazel_output_service.BazelOutputService.FinalizeBuild:output_type -> bazel_output_service.FinalizeBuildResponse
	12, // 26: bazel_output_service.BazelOutputService.BatchStat:output_type -> bazel_output_service.BatchStatResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto != nil {
		return
	}
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes[18].OneofWrappers = []any{
		(*BatchStatResponse_Stat_File_)(nil),
		(*BatchStatResponse_Stat_Symlink_)(nil),
		(*BatchStatResponse_Stat_Directory_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_bazeloutputservice_bazel_output_service_proto_depIdxs = nil
}
