// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/cas/cas.proto

package cas

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoricalExecuteResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActionDigest    *v2.Digest             `protobuf:"bytes,1,opt,name=action_digest,json=actionDigest,proto3" json:"action_digest,omitempty"`
	ExecuteResponse *v2.ExecuteResponse    `protobuf:"bytes,3,opt,name=execute_response,json=executeResponse,proto3" json:"execute_response,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HistoricalExecuteResponse) Reset() {
	*x = HistoricalExecuteResponse{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalExecuteResponse) ProtoMessage() {}

func (x *HistoricalExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalExecuteResponse.ProtoReflect.Descriptor instead.
func (*HistoricalExecuteResponse) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDescGZIP(), []int{0}
}

func (x *HistoricalExecuteResponse) GetActionDigest() *v2.Digest {
	if x != nil {
		return x.ActionDigest
	}
	return nil
}

func (x *HistoricalExecuteResponse) GetExecuteResponse() *v2.ExecuteResponse {
	if x != nil {
		return x.ExecuteResponse
	}
	return nil
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDesc = "" +
	"\n" +
	"@github.com/buildbarn/bb-remote-execution/pkg/proto/cas/cas.proto\x12\rbuildbarn.cas\x1a6build/bazel/remote/execution/v2/remote_execution.proto\"\xcc\x01\n" +
	"\x19HistoricalExecuteResponse\x12L\n" +
	"\raction_digest\x18\x01 \x01(\v2'.build.bazel.remote.execution.v2.DigestR\factionDigest\x12[\n" +
	"\x10execute_response\x18\x03 \x01(\v20.build.bazel.remote.execution.v2.ExecuteResponseR\x0fexecuteResponseJ\x04\b\x02\x10\x03B8Z6github.com/buildbarn/bb-remote-execution/pkg/proto/casb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_goTypes = []any{
	(*HistoricalExecuteResponse)(nil), // 0: buildbarn.cas.HistoricalExecuteResponse
	(*v2.Digest)(nil),                 // 1: build.bazel.remote.execution.v2.Digest
	(*v2.ExecuteResponse)(nil),        // 2: build.bazel.remote.execution.v2.ExecuteResponse
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_depIdxs = []int32{
	1, // 0: buildbarn.cas.HistoricalExecuteResponse.action_digest:type_name -> build.bazel.remote.execution.v2.Digest
	2, // 1: buildbarn.cas.HistoricalExecuteResponse.execute_response:type_name -> build.bazel.remote.execution.v2.ExecuteResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_init() }
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_cas_cas_proto_depIdxs = nil
}
