// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/completedactionlogger/completed_action_logger.proto

package completedactionlogger

import (
	v2 "github.com/bazelbuild/remote-apis/build/bazel/remote/execution/v2"
	cas "github.com/buildbarn/bb-remote-execution/pkg/proto/cas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompletedAction struct {
	state                     protoimpl.MessageState         `protogen:"open.v1"`
	HistoricalExecuteResponse *cas.HistoricalExecuteResponse `protobuf:"bytes,1,opt,name=historical_execute_response,json=historicalExecuteResponse,proto3" json:"historical_execute_response,omitempty"`
	Uuid                      string                         `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	InstanceName              string                         `protobuf:"bytes,3,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	DigestFunction            v2.DigestFunction_Value        `protobuf:"varint,4,opt,name=digest_function,json=digestFunction,proto3,enum=build.bazel.remote.execution.v2.DigestFunction_Value" json:"digest_function,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CompletedAction) Reset() {
	*x = CompletedAction{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedAction) ProtoMessage() {}

func (x *CompletedAction) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedAction.ProtoReflect.Descriptor instead.
func (*CompletedAction) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDescGZIP(), []int{0}
}

func (x *CompletedAction) GetHistoricalExecuteResponse() *cas.HistoricalExecuteResponse {
	if x != nil {
		return x.HistoricalExecuteResponse
	}
	return nil
}

func (x *CompletedAction) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CompletedAction) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *CompletedAction) GetDigestFunction() v2.DigestFunction_Value {
	if x != nil {
		return x.DigestFunction
	}
	return v2.DigestFunction_Value(0)
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDesc = "" +
	"\n" +
	"fgithub.com/buildbarn/bb-remote-execution/pkg/proto/completedactionlogger/completed_action_logger.proto\x12\x1fbuildbarn.completedactionlogger\x1a6build/bazel/remote/execution/v2/remote_execution.proto\x1a@github.com/buildbarn/bb-remote-execution/pkg/proto/cas/cas.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x94\x02\n" +
	"\x0fCompletedAction\x12h\n" +
	"\x1bhistorical_execute_response\x18\x01 \x01(\v2(.buildbarn.cas.HistoricalExecuteResponseR\x19historicalExecuteResponse\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12#\n" +
	"\rinstance_name\x18\x03 \x01(\tR\finstanceName\x12^\n" +
	"\x0fdigest_function\x18\x04 \x01(\x0e25.build.bazel.remote.execution.v2.DigestFunction.ValueR\x0edigestFunction2|\n" +
	"\x15CompletedActionLogger\x12c\n" +
	"\x13LogCompletedActions\x120.buildbarn.completedactionlogger.CompletedAction\x1a\x16.google.protobuf.Empty(\x010\x01BJZHgithub.com/buildbarn/bb-remote-execution/pkg/proto/completedactionloggerb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_goTypes = []any{
	(*CompletedAction)(nil),               // 0: buildbarn.completedactionlogger.CompletedAction
	(*cas.HistoricalExecuteResponse)(nil), // 1: buildbarn.cas.HistoricalExecuteResponse
	(v2.DigestFunction_Value)(0),          // 2: build.bazel.remote.execution.v2.DigestFunction.Value
	(*emptypb.Empty)(nil),                 // 3: google.protobuf.Empty
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_depIdxs = []int32{
	1, // 0: buildbarn.completedactionlogger.CompletedAction.historical_execute_response:type_name -> buildbarn.cas.HistoricalExecuteResponse
	2, // 1: buildbarn.completedactionlogger.CompletedAction.digest_function:type_name -> build.bazel.remote.execution.v2.DigestFunction.Value
	0, // 2: buildbarn.completedactionlogger.CompletedActionLogger.LogCompletedActions:input_type -> buildbarn.completedactionlogger.CompletedAction
	3, // 3: buildbarn.completedactionlogger.CompletedActionLogger.LogCompletedActions:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_completedactionlogger_completed_action_logger_proto_depIdxs = nil
}
