// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: github.com/buildbarn/bb-remote-execution/pkg/proto/tmp_installer/tmp_installer.proto

package tmp_installer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallTemporaryDirectoryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TemporaryDirectory string                 `protobuf:"bytes,1,opt,name=temporary_directory,json=temporaryDirectory,proto3" json:"temporary_directory,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstallTemporaryDirectoryRequest) Reset() {
	*x = InstallTemporaryDirectoryRequest{}
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallTemporaryDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallTemporaryDirectoryRequest) ProtoMessage() {}

func (x *InstallTemporaryDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallTemporaryDirectoryRequest.ProtoReflect.Descriptor instead.
func (*InstallTemporaryDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDescGZIP(), []int{0}
}

func (x *InstallTemporaryDirectoryRequest) GetTemporaryDirectory() string {
	if x != nil {
		return x.TemporaryDirectory
	}
	return ""
}

var File_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto protoreflect.FileDescriptor

const file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDesc = "" +
	"\n" +
	"Tgithub.com/buildbarn/bb-remote-execution/pkg/proto/tmp_installer/tmp_installer.proto\x12\x17buildbarn.tmp_installer\x1a\x1bgoogle/protobuf/empty.proto\"S\n" +
	" InstallTemporaryDirectoryRequest\x12/\n" +
	"\x13temporary_directory\x18\x01 \x01(\tR\x12temporaryDirectory2\xcf\x01\n" +
	"\x1bTemporaryDirectoryInstaller\x12@\n" +
	"\x0eCheckReadiness\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12n\n" +
	"\x19InstallTemporaryDirectory\x129.buildbarn.tmp_installer.InstallTemporaryDirectoryRequest\x1a\x16.google.protobuf.EmptyBBZ@github.com/buildbarn/bb-remote-execution/pkg/proto/tmp_installerb\x06proto3"

var (
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDescOnce sync.Once
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDescData []byte
)

func file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDescGZIP() []byte {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDescOnce.Do(func() {
		file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDesc)))
	})
	return file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDescData
}

var file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_goTypes = []any{
	(*InstallTemporaryDirectoryRequest)(nil), // 0: buildbarn.tmp_installer.InstallTemporaryDirectoryRequest
	(*emptypb.Empty)(nil),                    // 1: google.protobuf.Empty
}
var file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_depIdxs = []int32{
	1, // 0: buildbarn.tmp_installer.TemporaryDirectoryInstaller.CheckReadiness:input_type -> google.protobuf.Empty
	0, // 1: buildbarn.tmp_installer.TemporaryDirectoryInstaller.InstallTemporaryDirectory:input_type -> buildbarn.tmp_installer.InstallTemporaryDirectoryRequest
	1, // 2: buildbarn.tmp_installer.TemporaryDirectoryInstaller.CheckReadiness:output_type -> google.protobuf.Empty
	1, // 3: buildbarn.tmp_installer.TemporaryDirectoryInstaller.InstallTemporaryDirectory:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_init()
}
func file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_init() {
	if File_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDesc), len(file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_goTypes,
		DependencyIndexes: file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_depIdxs,
		MessageInfos:      file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_msgTypes,
	}.Build()
	File_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto = out.File
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_goTypes = nil
	file_github_com_buildbarn_bb_remote_execution_pkg_proto_tmp_installer_tmp_installer_proto_depIdxs = nil
}
